var characters = [
    {
        name: "Rover", 
        imageId: "dog-rover", 
        imageIdLit: "dog-rover-lit", 
        unlocked: true, 
        initiallyUnlocked: true,
        bio: "Rover is as loyal as they come. Likes playing fetch, long naps in sunbeams, and walks in the park. \n\n[good]All-around average dog\n[good]Great at accessorizing\n[bad]Goggles do nothing",
        initialWeapons: [WeaponPeashooter],
    },
    {
        name: "Hopper", 
        imageId: "dog-hopper", 
        imageIdLit: "dog-hopper-lit", 
        unlocked: false, 
        bio: "Hopper is an unharvested force of pure energy. Honestly the rocket probably wasn't needed to get him up here. \n\n[good]Reloads full-speed mid-air\n[good]Starts with a sweet jetpack\n[bad]Takes damage from landing",
        achievementGate: [{name: "beatGame", tier: 0}],
        midAirReload: true,
        damagedOnSolid: true,
        initialWeapons: [WeaponPeashooter, WeaponJetpack],
    },
    // {
    //     name: "Beans", 
    //     imageId: "dog-beans", 
    //     imageIdLit: "dog-beans-lit", 
    //     unlocked: false, 
    //     achievementGate: [{name: "beatGameMulticharacter", tier: 0}],
    //     bio: "Beans is a retired pageant dog who spent years competing to be the best. Old, but still ready for more adventures. \n\n[good]Heals when dealing damage\n[bad]Takes damage over time",
    //     mustKeepAttacking: true,
    //     initialWeapons: [WeaponShotgun],
    // },
    // {
    //     name: "Sparky", 
    //     imageId: "dog-sparky", 
    //     imageIdLit: "dog-sparky-lit", 
    //     unlocked: false, 
    //     achievementGate: [{name: "beatGameMulticharacter", tier: 999}],
    //     bio: "Sparky once ate an entire lasagna in one sitting. She considers this one of her crowning achievements. \n\n[good]Free samples in store\n[bad]Allergic to Mooney",
    //     damagedOnLoot: true,
    //     freeSamples: true,
    //     initialWeapons: [WeaponPeashooter],
    // },
    // {
    //     name: "Fritz", 
    //     imageId: "dog-fritz", 
    //     imageIdLit: "dog-fritz-lit", 
    //     unlocked: false, 
    //     achievementGate: [{name: "beatGameMulticharacter", tier: 999}],
    //     bio: "Fritz laughs at jokes even if they aren't funny. He just wants everyone to feel good about themselves. \n\n[bad]Poor eyesight, can't see\n[bad]enemies or coins\n[good]All weapons temporarily reveal\n[good]enemy positions\n[good](Radar Blast reveals a larger\n[good]area)",
    //     isBlind: true,
    //     maxHp: 1,
    //     initialWeapons: [WeaponPeashooter, WeaponRadarPing],
    // },
    // {
    //     name: "Natalie Terry & Goose", 
    //     imageId: "cats",
    //     imageIdLit: "cats-lit",  
    //     unlocked: false, 
    //     achievementGate: [{name: "beatGameMulticharacter", tier: 999}],
    //     bio: "Never send a dog to do a cat's job. Or three cats' jobs. Whatever. \n\n[good]Attack as a team \n[good]for massive damage!\n[bad]Friendly capsules share \n[bad]damage\n",
    //     followers: 2,
    //     initialWeapons: [WeaponPeashooter, WeaponFollowerGun],
    // },
    // {
    //     name: "MOG", 
    //     selectName: "<$NAME?>>>mogggg", 
    //     imageId: "dog-mog",
    //     imageIdLit: "dog-mog-lit",  
    //     imageIdLocked: "dog-mog-locked",
    //     unlocked: false, 
    //     isGlitchy: true,
    //     maxHp: 1,
    //     shipIndex: 7,
    //     noShops: true,
    //     achievementGate: [{name: "beatGameMulticharacter", tier: 999}],
    //     bio: "Hi there! You don't mind if I try plugging in to that capsule, right? \n\n[good]My stats are all good! \n[good]See, blue text! That's good!\n[good]Automatically wins!\n[good]Very sturdy!\n",
    //     initialWeapons: [WeaponPeashooter],
    // },
]