var characters = [
    {
        name: "Rover", 
        imageId: "dog-rover", 
        imageIdLit: "dog-rover-lit", 
        unlocked: true, 
        initiallyUnlocked: true,
        bio: "Rover is as loyal as they come. Likes playing fetch, long naps in sunbeams, and walks in the park. \n\n[good]All-around average dog\n[good]Great at accessorizing\n[bad]Goggles do nothing",
        victory: [
            "I did it! I knew I could!",
        ],
        failure: [
            "That's ok, I can try again!",
            "Don't worry, I'll do better next time!",
            "I think next time might be the one, can we try one more time?",
        ],
        maxHp: 10,
        shipIndex: 0,
        initialWeapons: [WeaponPeashooter],
    },
    {
        name: "Rex", 
        imageId: "dog-rex", 
        imageIdLit: "dog-rex-lit", 
        unlocked: false, 
        starCost: 15,
        bio: "Rex would much rather be at home curled up in front of the fireplace, but he has an overpowering sense of responsibiblity. \n\n[good]Grappling hook!\n[good]Ram enemies for damage\n[bad]Heavy capsule can't be\n[bad]propelled by anything except\n[bad]the grapple ",
        victory: [
            "Did good, yeah? Been long day, time for nap now.",
            "Job is done, can finally rest. Have warm place in sunbeam picked out. Very nice.",
        ],
        failure: [
            "We lose? We try again after nap. Come back refreshed. Yes?",
            "Did not get enough sleep last night. Need five more hours, then all good."
        ],
        achievementGate: [],
        bashDamage: true,
        grappleOnly: true,
        maxHp: 10,
        shipIndex: 1,
        initialWeapons: [WeaponGrapplingHook, WeaponBubbleShieldRex],
    },
    {
        name: "Beans", 
        imageId: "dog-beans", 
        imageIdLit: "dog-beans-lit", 
        unlocked: false, 
        starCost: 30,
        victory: [
            "Capital show! Gave those robots what for, eh?",
            "Heavens, to think those robots thought they stood a chance!",
        ],
        failure: [
            "Chin up, chin up, there's always next time.", 
            "Certainly can't let a minor setback be the end, eh, wot?",
            "We only truly fail when we give up. Another go, chap?",
        ],
        achievementGate: [],
        bio: "Beans is a retired pageant dog who spent years competing to be the best. Old, but still ready for more adventures. \n\n[good]Heals when dealing damage\n[bad]Takes damage over time",
        mustKeepAttacking: true,
        maxHp: 10,
        shipIndex: 2,
        initialWeapons: [WeaponShotgun],
    },
    {
        name: "Hopper", 
        imageId: "dog-hopper", 
        imageIdLit: "dog-hopper-lit", 
        unlocked: false, 
        starCost: 20,
        bio: "Hopper is an unharvested force of pure energy. Honestly the rocket probably wasn't needed to get him up here. \n\n[good]Reloads full-speed mid-air\n[good]Starts with a sweet jetpack\n[bad]Takes damage from landing",
        victory: [
            "Hey, that's what I'm talkin' about! I'm unstoppable!",
            "That's right! Robots gotta learn what happens when you mess with the best!",
        ],
        failure: [
            "What? Wait, we lost? That's not how it's supposed to go down!",
            "Hang on, hang on, let's try that one again. Best two outta three.",
            "Now that just ain't fair. They got LUCKY. Let me try again, I'll show ya!",
        ],
        achievementGate: [{name: "beatGame", tier: 0}],
        midAirReload: true,
        damagedOnSolid: true,
        maxHp: 15,
        shipIndex: 3,
        initialWeapons: [WeaponPeashooter, WeaponJetpack],
    },
    {
        name: "Sparky", 
        imageId: "dog-sparky", 
        imageIdLit: "dog-sparky-lit", 
        unlocked: false, 
        starCost: 30,
        victory: [
            "I'd say that's deserving of a celebratory dinner! Who's up for pasta?",
            "A job well done! Speaking of, I'll take my reward medium rare if you don't mind.",
        ],
        failure: [
            "No sense in trying again on an empty stomach, let's break for lunch.",
            "Another go, right after a small snack. Or a big snack, I'm open to big snacks, too.",
        ],
        achievementGate: [{name: "beatGame", tier: 0}],
        bio: "Sparky once ate an entire lasagna in one sitting. She considers this one of her crowning achievements. \n\n[good]Free samples in store\n[bad]Allergic to Mooney",
        damagedOnLoot: true,
        freeSamples: true,
        maxHp: 10,
        shipIndex: 4,
        initialWeapons: [WeaponFireCannon, WeaponFireGrenade],
    },
    {
        name: "Fritz", 
        imageId: "dog-fritz", 
        imageIdLit: "dog-fritz-lit", 
        unlocked: false, 
        starCost: 40,
        victory: [
            "A job well done, eh? Now that's music to me ears.",
        ],
        failure: [
            "I'll be frank, it don't sound like things went well.",
            "That crashing outside, I'm guessing that ain't a good sound, is it?",
        ],
        achievementGate: [{name: "beatGameMulticharacter", tier: 0}],
        bio: "Fritz laughs at jokes even if they aren't funny. He just wants everyone to feel good about themselves. \n\n[bad]Poor eyesight, can't see\n[bad]enemies or coins\n[good]All weapons temporarily reveal\n[good]enemy positions\n[good](Radar Blast reveals a larger\n[good]area)",
        isBlind: true,
        maxHp: 10,
        shipIndex: 5,
        initialWeapons: [WeaponPeashooter, WeaponRadarPing],
    },
    {
        name: "Natalie Terry & Goose", 
        imageId: "cats",
        imageIdLit: "cats-lit",  
        unlocked: false, 
        starCost: 50,
        victory: [
            "Of course, it's a great leader that makes a great team. Thank me at your leisure.",
        ],
        failure: [
            "Listen, I gotta be totally honest with you. This was all Goose's fault.",
            "Look, there's no easy way to say this so I'm just going to say it: Natalie screwed this one up.",
        ],
        achievementGate: [{name: "beatGameMulticharacter", tier: 0}],
        bio: "Never send a dog to do a cat's job. Or three cats' jobs. Whatever. \n\n[good]Attack as a team \n[good]for massive damage!\n[bad]Friendly capsules share \n[bad]damage\n",
        followers: 2,
        maxHp: 10,
        shipIndex: 6,
        initialWeapons: [WeaponPeashooter, WeaponFollowerGun],
    },
    {
        name: "MOG", 
        selectName: "<$NAME?>>>mogggg", 
        imageId: "dog-mog",
        imageIdLit: "dog-mog-lit",  
        imageIdLocked: "dog-mog-locked",
        unlocked: false, 
        starCost: 100,
        isGlitchy: true,
        maxHp: 1,
        shipIndex: 7,
        noShops: true,
        victory: ["Success. Complete success. Thank you."],
        failure: ["Abort, Retry, Fail?"],
        achievementGate: [{name: "beatGameMulticharacter", tier: 2}],
        bio: "Hi there! You don't mind if I try plugging in to that capsule, right? \n\n[good]My stats are all good! \n[good]See, blue text! That's good!\n[good]Automatically wins!\n[good]Very sturdy!\n",
        initialWeapons: [WeaponPeashooter],
    },
]