"use strict";
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
window.onload = Initialize;
var tiles = {};
var camera;
var currentMap;
var mouseHandler;
var editorHandler = new EditorHandler();
var uiHandler = new UiHandler();
var audioHandler;
var currentLevelCode = "";
function Initialize() {
    LoadImageSources();
    var canvas = document.getElementById("canvas");
    camera = new Camera(canvas);
    mouseHandler = new MouseHandler(canvas);
    audioHandler = new AudioHandler();
    audioHandler.Initialize();
    KeyboardHandler.InitKeyHandlers();
    CreateTestMap();
    setInterval(MainLoop, 1000 / 60);
}
function LoadImageSources() {
    var _a, _b;
    var container = document.getElementById("imageResources");
    var images = container === null || container === void 0 ? void 0 : container.querySelectorAll("img");
    if (images)
        for (var _i = 0, _c = Array.from(images); _i < _c.length; _i++) {
            var img = _c[_i];
            var src = img.src.split(".png")[0];
            var imgName = src.split("/")[src.split("/").length - 1];
            if (src.indexOf("/bg/") > -1)
                imgName = "bg_" + imgName;
            var tileMap = {};
            var rows = +((_a = img.dataset.rows) !== null && _a !== void 0 ? _a : 1) || 1;
            var cols = +((_b = img.dataset.cols) !== null && _b !== void 0 ? _b : 1) || 1;
            var rowHeight = img.height / rows;
            var colWidth = img.width / cols;
            for (var col = 0; col < cols; col++) {
                var tileCol = {};
                for (var row = 0; row < rows; row++) {
                    var imageTile = new ImageTile(img, col * colWidth, row * rowHeight, colWidth, rowHeight);
                    tileCol[row] = imageTile;
                }
                tileMap[col] = tileCol;
            }
            tiles[imgName] = tileMap;
        }
}
function MainLoop() {
    Update();
    Draw();
    audioHandler.Update();
    var perf = document.getElementById("perf");
    if (perf) {
        perf.innerHTML = BenchmarkService.GetReports();
        var otherData = document.getElementById("data");
        otherData.innerHTML = "Version: " + version;
        BenchmarkService.Log("IDLE");
    }
}
function Draw() {
    if (currentMap)
        currentMap.Draw(camera);
    MenuHandler.Draw(camera);
    BenchmarkService.Log("DrawEditor");
    if (editorHandler.isInEditMode)
        editorHandler.Draw(camera);
    BenchmarkService.Log("DrawUI");
    uiHandler.Draw(camera.ctx);
    BenchmarkService.Log("DrawDone");
}
var debugMode = false;
//var replayHandler: ReplayHandler | null; = new ReplayHandler();
//replayHandler.ImportFromBase64("ABcgGCQCNAg1BDEQIRUxBSEXIAwiBSAEIQYmAiIHJgIkAgQIJAIlAyEBMQERCDEBIQMgAyIJIAYkCAQDJAUgDSEcJAIiNAIFAAMQBwANEAgABRAEABUQDwAFEQkBHAADAgQyFyILMgM0AzEBEQoUARIDAg4ABQECEQMxCzIeOQExBiEFARgADQgGAAYIBAAFCAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
function Update() {
    var _a, _b, _c;
    //replayHandler.LoadFrame();
    KeyboardHandler.Update();
    MenuHandler.Update();
    var doesMenuBlockMapUpdate = (_a = MenuHandler.CurrentMenu) === null || _a === void 0 ? void 0 : _a.stopsMapUpdate;
    if (KeyboardHandler.IsKeyPressed(KeyAction.Fullscreen, true))
        (_b = document.getElementById("canvas")) === null || _b === void 0 ? void 0 : _b.requestFullscreen();
    if (KeyboardHandler.IsKeyPressed(KeyAction.Debug1, true))
        debugMode = !debugMode;
    //if (KeyboardHandler.IsKeyPressed(KeyAction.Reset, true)) window.location.reload();
    if (KeyboardHandler.IsKeyPressed(KeyAction.EditToggle, true)) {
        if (editorHandler.isInEditMode)
            editorHandler.SwitchToPlayMode();
        else if (editorHandler.isEditorAllowed)
            editorHandler.SwitchToEditMode();
    }
    if (debugMode) {
        if (KeyboardHandler.IsKeyPressed(KeyAction.Debug2, true)) {
            if (currentMap && !editorHandler.isInEditMode && !doesMenuBlockMapUpdate)
                currentMap.Update();
        }
        if (KeyboardHandler.IsKeyPressed(KeyAction.Debug3, true)) {
            var player_1 = currentMap.mainLayer.sprites[0];
            player_1.LoadHistory();
        }
    }
    else {
        //replayHandler.StoreFrame();
        if (currentMap && !doesMenuBlockMapUpdate) {
            if (editorHandler.isInEditMode) {
                currentMap.frameNum++;
                currentMap.mainLayer.Update();
            }
            else {
                currentMap.Update();
            }
        }
        if (currentMap && !doesMenuBlockMapUpdate && !editorHandler.isInEditMode && currentMap.CanPause() && !((_c = MenuHandler.CurrentMenu) === null || _c === void 0 ? void 0 : _c.blocksPause)) {
            var isOnMainMenu = MenuHandler.CurrentMenu instanceof MainMenu;
            if (KeyboardHandler.IsKeyPressed(KeyAction.Pause, true) && !isOnMainMenu) {
                var msSinceUnpause = (+(new Date()) - +PauseMenu.UnpauseTime);
                if (msSinceUnpause > 100)
                    MenuHandler.SubMenu(PauseMenu);
            }
        }
    }
    uiHandler.Update();
    editorHandler.Update();
    mouseHandler.UpdateMouseChanged();
    KeyboardHandler.AfterUpdate();
}
function CreateTestMap() {
    var mainLayer = new LevelLayer(TargetLayer.main);
    var wireLayer = new LevelLayer(TargetLayer.wire);
    var waterLayer = new LevelLayer(TargetLayer.water);
    var semisolidLayer = new LevelLayer(TargetLayer.semisolid);
    var backdropLayer = new LevelLayer(TargetLayer.backdrop);
    TileType.RegisterTiles();
    var map = new LevelMap(mainLayer, wireLayer, waterLayer, semisolidLayer, backdropLayer);
    currentMap = map;
    editorHandler.Update(); // need to run one update cycle to init + set "default" positions
    editorHandler.sprites.push(new EditorSprite(Player, { tileX: 4, tileY: 16 }));
    currentMap = LevelMap.FromImportString("0.11.0;77;0;0;6|#190000,#0c0c26,0.00,1.00,0.00;AL,#5eeded,0,0,0.1,-4,1,0;AK,#5eeded,0,0,0.3,8,0,0;AU,#bcd8db,0,0,0.2,-2,1,0;AC,#9b14b7,-10,0,0,-10,1,0|AAeAIGAA/AAEAIHAAJAGAAA5AIHAA/AAEAIHAA/AAEAIHAAJAGAAA5AIHAA/AAEAIHAA/AAEAIHAAJAGAAA5AIHAA/AAEAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAfAIHAAhAICAAgAIGAAm|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAD|BQfADAAAMDUEAASBQGAAfADAAAMDUBAAADUBAASBQADSAAACDSABQAAAMDXQAABADAAAMDUEAASBQADSAAACDSABQAAAfADAAAMDUEAASBQADSAAACDSABQAAAODXOAABDuAAAMDUBAAADUBAASBQADSAAACDSABQAAAUDXIAAPDUEAASBQADSAAACDSABQAAAJDXTAAPDUEAASBQADSAAACDSABQAAAtDUBAAADUBAASBQADSAAACDSABQAAAiDuAAAJDUEAASBQADSAAACDSABQAAAiADAAAJDUEAASBQADSAAACDSABQAAAMDXQAAEADAAAJADEAASBQADSAAACDSABQAAAiADAAAKADCAATBQADSAAACDSABQAAAiADAAALADAAAUBQADSAAACDSABQAAAaDXCAAEADAAAhBQADSAAACDSABQAAAJDXTAAEADAAAhBQADSAAACDSABQAAAiADAAAhBQADSAAACDSABQAAAODXOAAEADAAAhBQADSAAACDSABQAAAMDXQAAEADAAAhBQADSAAACDSABQAAAiADAAAhBQADSAAACDSABQjADAAAhBQG|AAlANAAAeANAAAPANAAABANAAAPANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAANANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAAEANAAAHANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAAEANAAACANAAADANAAAGANAAAeANAAADANAAAKANAAADANAAAEANAAACANAAADANAAAGANAAAeANAAADANAAAKANAAADANAAAEANAAACANAAADANAAAGANAAAeANAAADANAAAKANAAAJANAAACANAAADANAAAGANAAAeANAAADANAAAKANAAABANAAADANAAAFANAAADANAAAGANAAAeANAAADANAAAKANAAABANAAADANAAAKANAAAGANAAAeANAAADANAAAKANAAABANAAADANAAAKANAAAGANAAAeANAAADANAAAKANAAABANAAADANAAAHANAAABANAAAGANAAAeANAAADANAAAKANAAABANAAADANAAACANAAADANAAABANAAAGANAAAeANAAADANAAAKANAAAKANAAADANAAABANAAAGANAAAeANAAADANAAAKANAAADANAAAFANAAADANAAABANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAAFANAAADANAAABANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAAFANAAAGANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAANANAAAGANAAAeANAAADANAAAKANAAABANAAAAANAAANANAAAGANAAAeANAAADANAAAmANAAAeANAAAF|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAhAqAAA/AALAkAAA/AALAkAAA/AALAkAAA9AlNAoAAA/AA/AAs|AcALAzAF;BCAAAt;AKAIAi;AKASAd;ATAQBK;ATAMAx;AAAGBK;A1ANA5;BGANAX;BGAFAS;BGARAP;BGAJAK;BGAKAI;ABANAB");
    editorHandler.SwitchToPlayMode();
    __spreadArrays(editorHandler.editorParentElementsTop, editorHandler.editorParentElementsBottom).forEach(function (a) { return a.SnapToPlace(); });
    MenuHandler.CreateMenu(InitialMenu);
}
var player;
var isDemoMode = false;
var allDemoLevels = [
    "0.10.0;12;0;0;3|#00dddd,#eeeeff,0.00,1.00,0.40;AA,#ffffff,-0.25,0,0.05,0,0,0;AB,#5959a5,0,0,0.1,0,1,0;AC,#14b714,0,0,0.2,0,1,0;AD,#10a010,0,0,0.3,0,1,0|AA/AA/AA/AA/AAWABGAAEABGAAEABGAAEABGAAEABGAA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAQABEAAGABEAAGABEAAGABEAA/AA/AAWABEAAGABEAAGABEAAGABEAA/AA/AA/AA/AAH|AA/AA/AA/AA/AA/AA/AA/AA/AA/AAoADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAAEADAABFAA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA7|AAIABBACAAAIABCAAIACAABBAAIABAACAABAAAIABCAAIABCAAIABBACAAAIACAABBAAHAGAABCAAIABCAAIABCAAGABBACAABBAAGABEAAGABDACAAAGABEAAGABBACAABBAAGABEAAHABDAAHACAABAACAABAAAHABDAAHABDAAHABAACAABBAAHAIAABCAAIAIAABBAAJABBAAJACAABAAACAEGABBAAJABAACAAAJABBAAJABBAAIABCAAIABCAAIABBACAAAIABCAAtACAABAAAJABBAAJABBAAJABBAAfABDAAGAGAABDAAHABBACAABAAAHABDAAEABCACAABBACAAAEACAABFAAEABBACAABDAADBuAABEACAABAAADBuAAAFABAAADBuAAAFABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAEABGAAEABGAAEABGAAGABEAAGABEAAGABEAAIABCAAIABCAAIABCAAJABBAAJABBAAICIAABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAA/AA/AA/AA/AAcABCAAIABCAAIABCAAIABCAAIABCAAIABCAAIABCAAIABCAAIABCAAIABCAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABBAAJABB|AAIABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAIABAAAKABAAAKABAAAKABAAAKABAAAKABAAALABAAAKABAAAKABAAAKABAAAKABAAARABAAAKABAAAFABAAADABAAAFABAAADABAAAFABAAADABAAAFABAAAKABAAAKABAAAJABAAAKABAAAKABAAAKABAAAvABAAAKABAAAKABAAAKABAAAgABAAAKABAAAKABAAAKABAAAHABAAAKABAAAKABAAAKABAAAKACAAAKACAAA/AA/AA/AAiABAAAKABAAAKABAAAMABAAAKABAAAKABAAAMABAAAKABAAAKABAAALABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAHABAAABABAAAHABAAAKABAAAKABAAA/AA/AAaABAAAKABAAAKABAAAKABAAA8ABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAALABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAKABAAAA|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAP|ABCGAF;A6AYAC;AEAPAG;AEAgAI;AzAiAG;AzAjAF;AzAkAG;AEAxAE;AbA8AGAD;A0A9AC;AlA2AJ;AlA/AH;A5BIAE;AEBLAG;AEBOAI;A4BcAJ;AzBZAG;AzBYAG;AzBXAG;AEBiAG;AEBiAF;AdBoAIAD;AdBtAI;AEB0AG;AFCAAH;AAAEAI",
    "0.10.0;12;0;0;9|#00264c,#242474,0.00,1.00,0.55;AT,#001119,0,0,0.05,8,1,0;AT,#001419,0,0,0.1,-4,0,0;AT,#002c32,0,0,0.2,-2,1,0;AT,#0a2528,0,0,0.3,0,0,0|AA/AA/AASAJFAAFAJIAACAJIAACAJIAACAJFAA/AA/AAQAJBAAJAJBAAEAJGAAEAJGAAEAJGAATAJDAAHAJDAAIAJAAAKAJAAAKAJAAABAJEAADAJAAABAJEAADAJAAABAJJAABAJJAABAJJAAIAJCAA/AA/AASAJDAAHAJDAAHAJDAAHAJDAAHAJDAAHAJDAAHAJDAAHAJDAAHAJDAAHAJDAAHAJDAAFAJAAAAAJDAAFAJAAAKAJAAAKAJAAA/AA/AA4AEFAA/AACAEEAAnAEHAA/AAcAJAAAeAJEAAGAJEAAGAJEAAGAJEAAGAJEAAHAJDAAHAJDAAHAJDAAGAJEAAGAJEAAGAJEAAGAJEAAGAJEAA/AA/AA/AA/AA/AA/AA/AAWAJ/AJ/AJDAA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAT|AA/AA/AA/AA/AA/AAwAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAcAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAADAGAAFGAAEAGAAFFAAEAGAAFFAAEAGAAFFAAEAGAAFFAAUAGAAFAAAJAGAAFAAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAIAGAAFBAAgAGAAFAAAhAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAJAGAAFAAAEAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAACAGAAFHAA/AA/AA/AA/AA/AA/AA/AA/AAn|DsFD6AAABDsEDuADsCD7AAAADxADsHD1AAACDsGD6AAADDsGD7AAADDsGAAEDsDDuADsBAAEDsGAAEDsBDuADsDAAEDsCAAIDsCAAFDEAAABDsCAAFDEAAABDsCAAFDEAAABDsADuADsAAAIDsCAAIDsCAAIDsCAAFDEAAABDsBDuAAAFDEAAABDsCAAFDEAAABDuADsBAAIDsGAAEDsEDuADsAAAEDsGD8AAADDsBDuADsDD9AAADDsHAADDsHAADDsDDuADsCAADDsGD6AAADDsADuADsED7AAADDsED1AAAFD4ADsCD6AAAGD5ADsCD7AAAHDsCAAIDsCAAIDsCAAIDsADuADsAAAIDsCAACDsEAAADsCAACDsEAAADsCAACDsCDuADsAAAADsCAACDsEAAADsBDuAAACDsADuADsCAAADsCAACDsEAAADsCAACDsCAACDuADsBAACDsCAACDsCAABDxADsBDuAAACDsCAACDsIAACDuADsFDuADsAAAGDzADsDAAHDsDAAHD4ADsCAAHD5ADsCAAIDsGAAEDsADuBDsDAAED4ADsFAAED5ADsGAAEDsFDuAAACDwBDsBAACDsBAAEDsBAACDsBAAEDsBAACDsBAAEDsBAAJDsBAAJDsBAAJDsBAAJDsBAAJDsBAAJDsBAACDsBAAEDsBAACDsBAAEDsBAACDuADsAAAEDsGAACDwBDsBDuADsDAAEDsEEFAEEAAADDsCD1AAAGDwADsBD6AAAIDsBD7AAAHDsBDuAAAEDsGAAEDsBDuADsDAADDuADsGAADDsFDuADsAAADDsBDuADsEAADDsGDuAAADDsDDuADsCAAGDsEAAFDxADsEAAIDsBDuAAAIDsCAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDsAAAKDuAAAKDsAAAKDsAAAKDsAAAKDsAAADDsHAADDsADuADsCDuADsBAADDsDAAADsCAADDsHAADDsEDuADsBAAIDsCAADDvCAABDsCAADDvEDsCAAGDvBDsCAAIDsCDuADsDD0AAACDsIAACDsDDuADsCD1AAACDsCAAIDsCAAFDvCDsCAADDvEDsCAADDvCAABDsCAAIDsCAACDsIAACDuADsBD1AAABDuADsBAACDsCAACDsCAACDsADuADsAAACDsCAAeDwBAAKDwAAAJDwEAAEDwCAABDwAAA0DwCAAEDwEAAKDwCAAKDwBAAKDwBAAJDwAAA5DwAAAKDwCAAKDwDAAGDwBAAIDwBAAJDwAAAKDwAAAoDsFAAGDxADsEAAEDsDDuADsBAAEDsHAACDwADsFDuADsAAACDwADsHAACDwADsADuADsEAADDwADsGAADDwADsFAAEDwAAAJDwBAAADvBAAHDwAAAADvBAAFDwCAAIDwAAAADwADsFAAEDwADsGAADDwADsADuADsEAADDwADsHAACDwADsHAACDwADsDDuADsCAACDwADsGAADDwAAAKDwAAAJDwBAAIDwCAADDsCDwCDsBAADDsHAACDsIAACDsFDuADsBAACDsIAACDsCDuADsEAACDsIAACDsIAAIDEAAAKDEAAAKDEAAABDsAECAEDAAAIDsED0AAADDEAAAADuADsEAADDEAAAADsED1AAADDEAAAADsCDuADsAAAGDsCEFAEEAAADDEAAAKDEAAAKDEAAATDEAAAKDEAAAKDEAAAmDEAAADDEAAAKDEAAAKDEAAAFDEAAADDEAAAKDEAAAKDEAAAFDEAAAKDEAAAbDEAAAEDEAAAEDEAAAEDEAAAEDEAAAJDsCAAIDsCAAIDsCAADDuADsBAABDECAADDuADsBAABDECAADDuADsBAABDECAADDuADsBAABDECAADDuADsGAADDuADsGAADDuADsGAADDuADsB|AAIAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAASAOAAAKAOAAADAOAAAFAOAAADAOAAAKAOAAAIAOAAAAAOAAAIAOAAAAAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAEAOAAAKAOAAA/AA/AACAOAAAKAOAAAKAOAAA/AASAOAAAKAOAAAKAOAAA/AATAOAAAKAOAAAJAOAAAKAOAAAKAOAAAKAOAAAKAOAAANAOAAAKAOAAAMAOAAAGAEAAACAOAAAGAEAAAKAEAAAvAEAAAKAEAAAKAEAAATAEAAAKAEAAAKAEAAA7AOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAADAOAAAFAOAAADAOAAAFAOAAADAOAAAFAOAAADAOAAAFAOAAADAOAAAKAOAAAKAOAAAKAOAAAFAOAAADAOAAAFAOAAADAOAAAFAOAAADAOAAAFAOAAADAOAAAFAOAAADAOAAAEAOAAAKAOAAAKAOAAAKAOAAA/AA/AA/AA/AA/AA9AOAAA/AA/AA/AA/AAIAOAAAKAOAAAJAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAA/AA/AA/AA/AA/AAxAOAAAKAOAAAKAOAAAFAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAKAOAAAB|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAL|ABDbAG;A6AOAC;AJAqAD;A0ArAI;AzA7AC;AzA5AC;AzA6AC;AzBDAC;AzBCAC;AzBEAC;AbA+AFAC;AJBRAD;AJBgAC;A5BxAI;AoCWAJ;AoCLAE;AlClAF;AlCOAH;AzCcAJ;AzCeAJ;AzCgAJ;AzCQAC;AzCSAB;AzCUAC;AzCBAB;AzCDAC;AzB/AC;A6B6AI;A0DNAH;AAAEAI;AJC1AC",
    "0.10.0;19;0;0;4|#b25900,#0c0c26,0.00,1.00,0.50;AT,#481f03,0,0,0.05,8,1,0;AT,#b24a00,0,0,0.1,-4,0,0;AT,#993f00,0,0,0.2,-2,1,0;AT,#b77314,0,0,0.3,0,0,0|ADJAADADOAADADOAADADOAADADOAADADOAADADEAANADEAANADEAANADEAASADCAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAAFADMAA/AA/AAUADDAAOADDAAOADDAAOADDAAOADDAAOADDAAOADDAAOADDAA/AA/AA/AA/AArAD/ADxAAS|AA/AA/AA/AA/AA/AA/AA/AAaAEPAACAEPAA/AA/AA/AA/AA/AA/AA/AA/AA/AA1|AAABIABHABLABMAAAABIABHABLABMAACAAABACABLABHABLABHABLAAAAA1DAAAA1DACAAABACABOABKABOABKABOAAAAA1DAAAA1DACAAABACABHABLABHABLABHAAAABJABKABOABNAAAABJABKABOABNAACAAABACABKABOABKABOABKABHABLABMAAAABIABHABLABMAAAABIAACAAABACABLABHABLABHABLAA1CAAAA1DAAAA1AACAAABACABOABKABOABKABOAACKAABACABHABLABHABLABHAAAMACABKABOABKABOABKAAAMACABLABHABLABHABLAACDAADACKBLABHABLAACAAADACAAAABIABHABLABMAAAABIABHABLABMABOABKABOAACAAADACAAAAA1DAAAA1DBHABLABHAACAAADACAAAAA1DAAAA1DBKABOABKAACAAADACAAAABJABKABOABNAAAABJABKABOABNABLABHABLAACAAADACABHABLABMAAAABIABHABLABMAAAABIABOABKABOAACAAADACAA1CAAAA1DAAAA1ABHABLABHAACAAADACAA1CAAAA1DAAAA1ABKABOABKAACAAADACABKABOABNAAAABJABKABOABNAAAABJABLABHABLAACAAADACAAAABIABHABLABMAAAABIABHABLABMABOABKABOAACAAADACAAAAA1DAAAA1DBHABLABHAACAAADACAAAAA1DAAAA1DBKABOABKAACAAADACAAAABJABKABOABNAAAABJABKABOABNAACDAADACKAAPACCAAPACCAAPACCAAPACCAAPACCAAPACCAAAACKAACACDAADA1GACAAACACDAADA1GACAAACACDAADA1GACAAAKA1GACAAAKA1GACAAAKA1GACAAAKA1GACAAACACDAADA1GACAAACACPAACACDAAyACFAALDHAACFAAMACFAA/AA/AAXACLAAGACLAA/AASACl|AA/AA4ALCAA3AMCAAhAKAAARAKAAARAKAAARAKAAARAKAAARAKAAARAKAAARAKAAARAKAAARAKAAA/AKAAARAKAAARAKAAARAKAAARAKAAARAKAAA2ALDAA/AAaAMDAA/AAYAKAAARAKAAARAKAAA/AA/AAvALLAA/AASAMMAAY|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAz|ABA3AD;AmAPAG;AmAPAF;AmAPAE;AmAPAD;AmAPAC;ADAjAB;ADAhAQ;AAACAM;AmAfAN;AmAtAK;AmAtAI;AmAtAG;AdAtANAD;AdAxAOAD;AdA1AO",
    "0.10.0;12;0;0;10|#007f99,#000019,0.00,1.00,0.25;AH,#0c0c0c,0,0,0.05,4,1,0;Aa,#191919,0,0,0.2,-2,0,0;AZ,#333333,0,0,0.3,-1,0,0;Aa,#4c4c4c,0,0,0.4,-5,0,0|AA/AA/AA/AAvAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAVAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAAJAIBAA/AA/AA/AA/AA/AA/AAt|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/|DTCDUAAADDUADTCDVCDSAAADDSAAACDVCDSAAADDSAAACDVCDSADXAAACDSAAACDVCDSAAADDSAAACDVCDSAAADDSAAACDVCDSAAADDSAAACDVCDSAAADDSAAACDVCDSAAADDSAAACDVCDUAAADDUADTCDVCDSAAAEDWADTAAAADVCDSAAAEDWADTAAAADVCDSAAAEDWADTAAAADVCDSAAAEDWADTAAAADVCDUAAADDUADTCAAHDSAAAKDSAAAKDSAAAKDSAAAKDUADTFAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAIDTCAAIDVBDTAAAIDTCAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAKDTAAAIDTCAAoDUADTCAAHDSADVCAAHDSADVCAAHDSADVCAAHDSADVCAAHDUADTCAARDUADTEAAFDSADVEAAFDSADVEAAFDSADVEAAFDSADVEAAFDUADTEAA3DUADTCAAHDSADVCAAHDSADVCAAHDSADVCAAHDSADVCAAHDUADTCAAeDUADTDAAGDSADVDAAGDSADVDAAGDSADVDAAGDSADVDAAGDUADTDAAX|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/|AA/AA/AA/AA8AqAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAsAAAuAqAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAkAAAKAsAAA/AA/AA/AAXADDAA/AA/AA/AAd|AvAVAB;AvArAB;AbAqAI;AbAUAI;AzAhAF;AzAgAE;AzAfAF;A4A7AF;A4AOAC;A2A9AC;AzAyAE;AzAxAE;AzAxAF;AzAyAF;ABBKAD;AAAEAH",
    "0.10.0;19;0;0;0|#007f99,#000019,0.00,1.00,0.25;AH,#442c07,0,0,0.05,4,1,0;AG,#442c07,0,0,0.1,0,1,0;AG,#442c07,0,0,0.2,-2,0,0;AD,#29a010,0,0,0.3,1,0,0|AA/AA/AAhACFAA/AAEABDAAOABDAAOABDAAiACDAA/AA8ACDAA/AA/AAlABNAAEABNAAEABNAAEABNAA/AA/AA/AA/AA/AA/AA/AAH|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAz|ABIAADABOBUCAAAABOBUDABOAADABOBUBAABABPAACABPAABBUAABPAAFABMAAFABMAAFABMAAFABMAADBUBABMAABABQAABABQBUAAAAABQAADABOAADABOAADABOAADABNAAEABNAAEABKBUBAAFABKAAGABLAADABOAACABPAACABCAAGABFAAMABFAADAFABUHABFAAMABFAAMABFAADAFABUHABFAAMABFAAMABFAAFAFABUFABFAAFAFABUFABFAAMABFAAMABFAADAFABUHABFAAMABFAAMABFAACABJAAIABJAAIABJAAIABJAA/AALABBAAFABLBUCAADABMAACBUCABMAAFABMBUBAAEABLAAEBUBABLAAGABLAAFBUAABMBUBAACABNAACBUBABOBUAAACABQAABABK|AAMABAAARABAAARABAAARABAAARABAAARABAAANAIAAACABAAANAIAAAFABAAAKAIAAAFABAAAKAIAAAFABAAAKAIAAAFABAAAKAIAAAFABAAAKAIAAABABAAAOAIAAABABAAAOAIAAABABAAAOAIAAARAIAAARAIAAA/AA/AASAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAARAIAAACABAAARABAAARABAAARABAAA/AAcABAAARABAAARABAAARABAAASABAAARABAAARABAAARABAAAQABAAARABAAARABAAARABAAAJ|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAz|AAADAM;AEARAN;AEAUAN;AnAeAJ;ADAhAJ;AIAhAL;AIAiAL;AnAbAJ;AnAlAJ;ABA1AE",
    "0.10.0;12;0;0;7|#18ffff,#ffd37f,0.00,0.65,0.40;AJ,#5eeded,-3.75,0,0.05,-2,1,0;AB,#5959a5,-3.5,0,0.1,-4,1,0;AJ,#5eeded,-7.75,0,0.2,-3,1,0;AJ,#5eeded,-10,0,0.3,-5,1,0|AA3AHAAAiAHAAA/AAdAHAAAiAHAAA/AAAAHGAA/AA8AHGAA/AA/AATAIHAADAIIAACAIIAACAIIAACAIIAACAIIAACAIIAACAIIAACAIIAACAIIAACAIIAACAIIAACAIIAA/AAWAIIAACAIIAACAIIAACAIIAACAIIAA/AA/AA/AA/AA/AA/AA/AAEAHAAAiAHAAA/AA4AHAAAiAHAAA/AAcAHAAAiAHAAA/AAY|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAL|AATADAClAAAJCkAADAAAKADAAAJDTAADAAAJDTAADAAAJDTAADAAAJDTAADAAAKADAAAsADAClAAAJCkAADAAAKADAAAJDTAADAAAJDTAADAAAJDTAADAAAJDTAADAAAKADAAACADAAAKADAAAKADAAAKADAAAGBQAAACADADXGBQAAACADAAAGBQAAACADAAAGBQAAACADAAAGBQAAACADAAAEBqBBQAAACADAAAEBqBBQAAACADAAAFBqABQAAACADAAAGBQAAACADAAAGBQAAACADAAAGBQAAACADAAAGBQAAACADADXGBQAAACADAAAGBQAAACADAAAKADAAAKADAAAcADBClAAAIADBCeAClAAAHCkACeAADBCtAAAHCkAADBCuAAAIADCCtAAAHADCCuAAAHADIDXCADDDSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAGBqAADADSAADADSAAAGBqAADADSAADADSAAAHADCDTADaAAAFDYADTAAABDZADTADXFDTADbAAACDSAAAFDTAAADDSAAAFDTAAADDSAAAFDTAAACDYADTADXFDTADaAAABDTADbAAAFDZADTAAABDSAAAHADCDSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADCDTAAAKDTAAAKDTAAAKDTAAAGADDDTAAAGADADSAADADSADTAAAGADADSAADADSADTAAAGADADSAADADSADTAAAGADADSAADADSADTAAAGADADSAADADSBAAEDTAAAAADADSAADADSBAAEDTAAAAADADSAADADSBAAEDTAAAAADADSAADADSBAAEDTAAAAADADSAADADSBDXDAAADTAAAAADADSAADADSBAAEDTAAAAADADSAADADSBAAEDTAAAAADADSAADADSBAAEDTAAAAADDDSAAAEDTAAAADUDDSAAAEDTAAAAADDDSAAADDYADTAAAAADADSAADADSBAACDYADTADbAAAAADCDSBAACDTADbAAACDSAADADSBDXCDTAAADDSAADADSADTEAADDSAADADSAAADDTADaAAACDSAADADSAAADDZADTADaAAAAADCDSAAAEDZADTAAAAADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAAHADADSAADADSAAApADAClAAAJCkAADAAAKADAAAJDTAADAAAJDTAADAAAJDTAADAAAJDTAADAAAKADAAA/AAHADAClAAAJCkAADAAAKADAAAJDTAADAAAJDTAADAAAJDTAADAAAJDTAADAAAKADAAArADAClAAAJCkAADAAAKADAAAJDTAADAAAJDTAADAAAJDTAADAAAJDTAADAAAKADAAA/AAL|AA3AFAAAAAFAAAIAFAAJAAFAAAIAFAAJAAFAAAIAFAAAAAFAAA/AAbAFAAAAAFAAAIAFAAJAAFAAAIAFAAJAAFAAAIAFAAAAAFAAA5ANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAAKANAAA/AA/AA/AA/AA/AACAJAAAKAJAAAKAJAAA/AA/AAwAFAAAKAFAAAEAJAAAKAJAAAKAJAAAKAJAAAKAJAAAKAJAAAKAJAAAKAJAAAKAJAAAKAJAAAKAJAAA/AA/AA/AAcAFAAAAAFAAAIAFAAJAAFAAAIAFAAJAAFAAAIAFAAAAAFAAA/AA2AFAAAAAFAAAIAFAAJAAFAAAIAFAAJAAFAAAIAFAAAAAFAAA/AAaAFAAAAAFAAAIAFAAJAAFAAAIAFAAJAAFAAAIAFAAAAAFAAA/AAW|AA/AAoABAAA/AA/AABABAAA/AA/AA/AA/AA8ABAAAKABAAA/AACABAAAKABAAAWABAAAKABAAA/AA/AA/AA/AA/AAZADAAAKADAAAFADAAADADAAAFADAAADADAAAFADAAADADAAAFADDAXAADAAAFADAAAKADAAAKADAAAKADAAA/AAvABAAA/AA/AAAABAAA/AA/AAcABAAA/AA/AAAABAAA/AAL|ABCHAC;ApAJAH;ApAUAG;AqAZAF;AHAkAH;ApAvNaAN;ApAuNaAN;ApAvAA;ApAuNaAN;ApAuAA;AqBGAH;AqBGAF;ApA0AI;ApA4AI;ArBLAG;ApBUAH;ApBWAH;ApBYAH;ArBgAI;ApBWAC;AfBeAD;ApBoAH;ApBzAF;ApCAAH;ArB9AE;ArCBAH;ApCLAF;ArCJAF;AAAEAH",
    "0.10.0;19;0;0;0|#ffe464,#eeeeff,0.10,1.00,0.45;AB,#cbb130,0,0,0,-3,1,0;AI,#e5d418,0,0,0,-2,1,0;AA,#ffffff,-0.25,0,0,-5,0,0;AM,#c68605,0,0,0.3,-1,1,0|AA/AA/AA/AA/AA/AA/AA/AA/AALACEAA/AAGABEAAIACCAABACEAANABEAANABFAAMABFAAKABHAAMABFAAMABFAAMABEAAIACCAABACEAANABEAA/AA/AA/AA/AA/AAq|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAMAECAAPAECAAPAECAA/AA/AA/AAP|AAQA1BAAQA1BAAQA3AA1AAAQA1BAAQA1BAAQA1BAAPA/AA1BAAPBAAA1BAAOA/AA1BA3AAANA5AA3AA1CAAOA1DAAOA1DAAOA1DAAOA1AA3AA1BAAOA1DAAOA1DAAOA1DAAOA1DAAMA5BA1DAAOA3AA1CAAOBBAA1CAAOBCAA1AA3AA1AAAPA1CAAPBBAA1BAAPBCAA1BAAQA1BAAQA1BAAJA3AAAEAdAA1BAAJA2AAAEAdAA2AA1AAAJA2AAAEAdAA2AA1AAAJA2AAAEAdAA2AA1AAAIA2BAAEAdAA2AA1AAAFA2AAABA2BAAEAdAA2AA1AAAFA2AAABA2BAAEAdAA2AA1AAAFA2AAABA2BAAFA2AA1AAAFA2AAABA2BAAFA2AA1AAAFA2AAABBsCAAEA2AA1AAAFA2AAABA2BAAFA2AA1AAAFA2AAABA2BAAFA2AA1AAAFA2AAABA2BAAEAdAA2AA1AAAFA2AAABA2BAAEAdAA2AA1AAAIA2BAAEAdAA2AA1AAAPA1CAAPA1CAANA5BA1CAAPA1CAAPA1CAA/AAIA1CAAPA1CAANC9DA1AAANC9DA1AAANC9DA1AAANC9DA1AAAQA1BAAQA1BAAQA1BAAQA1BAALA5EA1B|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AAF|AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AA/AApADDAAOADDAAOADDAAOADDAARADAAARADAAARADAAAl|AFAkAP;AEAPAN;ABA1AP;AfA6AQ;AHA3AN;AAAEAQ;A0AkAD;A0AiAD;A0AmAD",
];
var currentDemoIndex = 0;
