class WeaponFireGrenadeEffect extends Weapon {
    name = "Fire Bomb Effect";
    flavor = "Effect generated by fire bomb. "
    fireSound = "ow-01";

    pelletSpeed = 0.2;
    fixedSpread = false;
    clipSize = 1;
    pelletCount = 24;
    pierce = 10;
    pelletSpread = Math.PI * 2;
    pelletType = PlayerFlame;
    pelletDuration = 60 * 6;
    holsterReloadRatio = 1;
    midAirReloadRatio = 1;
    effectDuration = 60 * 2;
    pelletGravityScale = 0.125;
    pelletSpeed = 0.125;
    
    upgrades = [
        Upgrade.PelletDurationScale(20, 0.3),
        Upgrade.PelletDurationScale(20, 0.3),
    ]
}