class WeaponMagnetPulse extends Weapon {
    name = "Ferrous Wheel Effect";
    flavor = "Effect generated by magnet bomb. "
    fireSound = "pew-02";

    pelletSpeed = 0.2;
    fixedSpread = true;
    clipSize = 1;
    reloadSpeed = 0.08;
    kickbackPower = 0;
    pelletCount = 24;
    cost = 25;
    pierce = 10;
    pelletSpread = Math.PI * 2;
    pelletType = PlayerMagnetPellet;
    pelletDuration = 60 * 3;
    holsterReloadRatio = 1;
    midAirReloadRatio = 1;
    effectDuration = 60 * 2;
    pelletGravityScale = 0;
    
    upgrades = [
        Upgrade.PelletSpeedScale(50, 0.2),
        Upgrade.PelletsScale(60, 0.3),
        Upgrade.EffectDurationScale(60, 0.3),
        Upgrade.PelletDurationScale(80, 0.3),
        Upgrade.PelletsScale(80, 0.3),
        Upgrade.EffectDurationScale(90, 0.3),
        Upgrade.PelletDurationScale(100, 0.3),
        Upgrade.PelletSpeedScale(120, 0.2),
    ]
}