var spriteTypes: SpriteType[] = [
    Player,
    GoldGear,
    CopperGear,
    IronGear,
    Piggle,
    Biggle,
    Snail,
    Prickle,
    PrickleEgg,
    Snouter,
    PricklySnouter,
    Spurpider,
    Shrubbert,
    SnowtemPole,
    Snoworm,
    BouncingSnowWorm,
    Baseball,
    Battery,
    Dice,
    Door,
    Fan,
    Key,
    Lightbulb,
    Umbrella,
    SnailShell,
    BouncePlatform,
    CloudPlatform,
    FloatingPlatform,
    RisingPlatform,
    ShakyPlatform,
    WeightedPlatform,
    Lever,
    FloorButton,
    LeftSideButton,
    RightSideButton,
    CeilingButton,
    DrSnips,
    AFish,
    BeeWithSunglasses,
    PrickleShell,
    AirBubble,
    Propeller,
    PorcoRosso,
    PorcoBlu,
    PorcoVerde,
    BlueCannon,
    Ring,
    Motor,
    SlowMotor,
    FastMotor,
    Rocket,
    Coin,
    Dabbloon,
    UpwardMotor,
    Sparky,
    RedBalloon,
    Hoggle,
    Checkpoint,
    ExtraHitHeart,
    MushroomPlatform,
    BlueBalloon,
    YellowBalloon,
    GreenBalloon,
    RedCannon,
    PrickleRock,

    CameraLockHorizontal,
    CameraScrollUp,
    CameraScrollDown,
    CameraScrollLeft,
    CameraScrollRight,

    Yufo,

    CameraZoomOut,
    CameraZoomIn,

    Clammy,
    Lurchin,
    Pufferfish,

    FlatKey,
    SapphireSnail,
    
    OrangeShrubbert,
    Yoyo,
    Wooly,
    WoolyBooly,
    GoldHeart,
    PogoPiggle,

    CameraScrollReset,
    SpringBox,
    Winch,
    PullSwitch,
    LittleJelly,
    
    FerrisMotorRight,
    FerrisMotorLeft,
    FastFerrisMotorRight,
    FastFerrisMotorLeft,
    Splatform,
    MushroomSpring,
    ChillyJelly,
    BigYufo,
    SpinRing,
    FragileSpinRing,
    ReverseWinch,
    
    Orbbit,
    Keplurk,
    Blaster,
    BaddleTrigger,
    Saw,
    SmallSaw,

    HoverPlayer,
    PurpleCannon,
    ReviveWings,

    SpinRingRight,
    SpinRingDown,
    SpinRingLeft,
    FragileSpinRingRight,
    FragileSpinRingDown,
    FragileSpinRingLeft,

    PortalRing,
    PortalRingRight,
    PortalRingDown,
    PortalRingLeft,
    
    CameraLockVertical,

    WindTriggerRight,
    WindTriggerDown,
    WindTriggerLeft,
    WindTriggerUp,
    WindTriggerReset,
    Doopster,
    Dabbot,
    ClimbingSpurpider,
    ControlledWinch,

    Bigby,
    SoccerBall,
    BowlingBall,
    Wallop,
    WallopPlatform,
    Wallopeño,
    WallopSlider,
    WallopPlatformSlider,
    BigWallop,
    BigWallopSlider,
    BigWallopPlatform,
    BigWallopPlatformSlider,

    GunPickup,
    Skitter,
    Bomb,
    SafetyBomb,
    BubbleKey,
    Escarghost,
    RubySnail,
    WaterBalloon,
    SpicyJelly,
    Angler,
    Vinedicator,
    GrayGrowth,
];