class WeaponFireGrenadeEffect extends Weapon {
    name = "Fire Bomb Effect";
    flavor = "Effect generated by fire bomb. "
    fireSound = "ow-01";

    fixedSpread = false;
    clipSize = 1;
    pelletCount = 24;
    pierce = 10;
    pelletSpread = Math.PI * 2;
    pelletType = PlayerFlame;
    pelletDuration = 60 * 6;
    holsterReloadRatio = 1;
    midAirReloadRatio = 1;
    pelletGravityScale = 0.125;
    pelletSpeed = 0.125;
    
    upgrades = [
        Upgrade.PelletSpeedScale(50, 0.2),
        Upgrade.PelletsScale(60, 0.3),
        Upgrade.PelletDurationScale(80, 0.3),
        Upgrade.PelletsScale(80, 0.3),
        Upgrade.PelletDurationScale(100, 0.3),
        Upgrade.PelletSpeedScale(120, 0.2),
    ]
}