var minigameAnswers = {
    "SNES Games": [
        "Arkanoid",
        "Breath of Fire",
        "Cameltry",
        "Chrono Trigger",
        "Donkey Kong Country",
        "Donkey Kong Country 2: Diddy's Kong Quest",
        "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
        "Dragon Quest",
        "EarthBound",
        "Earthworm Jim",
        "Final Fantasy IV",
        "Frogger",
        "Harvest Moon",
        "Illusion of Gaia",
        "Joe & Mac",
        "John Madden Football '93",
        "Killer Instinct",
        "Kirby Super Star",
        "Kirby's Avalanche",
        "Kirby's Dream Course",
        "The Legend of the Mystical Ninja",
        "The Legend of Zelda: A Link to the Past",
        "Lemmings",
        "The Lost Vikings",
        "Mario Is Missing!",
        "Mario Paint",
        "Mario's Early Years!",
        "Mario's Time Machine",
        "Mega Man 7",
        "Mega Man X",
        "Mickey Mania",
        "Mortal Kombat 3",
        "Pac-Attack",
        "Pilotwings",
        "Secret of Evermore",
        "Secret of Mana",
        "Star Fox",
        "Super Bomberman",
        "Super Double Dragon",
        "Super Mario All-Stars",
        "Super Mario Kart",
        "Super Mario RPG: Legend of the Seven Stars",
        "Super Mario World",
        "Super Metroid",
        "Tecmo Super Bowl",
        "Tetris Attack",
        "Uniracers",
        "Wario's Woods",
        "Where in the World Is Carmen Sandiego?",
        "WWF Super WrestleMania",
        "Yoshi's Cookie",
        "Yoshi's Island",
        "Yoshi's Safari",
        "Zombies Ate My Neighbors"
    ],
    "N64 Games": [
        "1080° Snowboarding",
        "Banjo-Kazooie",
        "Banjo-Tooie",
        "Blast Corps",
        "Bomberman 64",
        "Bomberman 64: The Second Attack",
        "Bomberman Hero",
        "Castlevania",
        "Diddy Kong Racing",
        "Donkey Kong 64",
        "Dr. Mario 64",
        "Duke Nukem 3D",
        "Gex: Enter the Gecko",
        "Glover",
        "Harvest Moon 64",
        "Hey You, Pikachu!",
        "Kirby 64: The Crystal Shards",
        "The Legend of Zelda: Majora's Mask",
        "The Legend of Zelda: Ocarina of Time",
        "Mario Golf",
        "Mario Kart 64",
        "Mario Party",
        "Paper Mario",
        "Paperboy 64",
        "Pilotwings 64",
        "Pokemon Puzzle League",
        "Pokemon Snap",
        "Pokemon Stadium",
        "Quest 64",
        "Space Station Silicon Valley",
        "Star Fox 64",
        "Super Mario 64",
        "Super Smash Bros.",
        "Superman 64",
        "Tetrisphere",
        "Turok: Dinosaur Hunter",
        "Wipeout 64",
        "Yoshi's Story"
    ],
    "GCN Games": [
        "Beyond Good & Evil",
        "Bomberman Generation",
        "Custom Robo",
        "Donkey Kong Jungle Beat",
        "Donkey Konga",
        "Final Fantasy Crystal Chronicles",
        "Gauntlet Dark Legacy",
        "Harvest Moon: A Wonderful Life",
        "James Bond 007: Agent Under Fire",
        "James Bond 007: Everything or Nothing",
        "Kirby Air Ride",
        "The Legend of Zelda: The Wind Waker",
        "The Legend of Zelda: Twilight Princess",
        "Luigi's Mansion",
        "Mario Golf: Toadstool Tour",
        "Mario Kart: Double Dash",
        "Mario Power Tennis",
        "Metroid Prime",
        "Metroid Prime 2: Echoes",
        "Paper Mario: The Thousand-Year Door",
        "Pikmin",
        "Pokemon Colosseum",
        "Sonic Adventure 2 Battle",
        "Star Fox Adventures",
        "Super Mario Strikers",
        "Super Mario Sunshine",
        "Super Monkey Ball",
        "Tales of Symphonia",
        "TimeSplitters: Future Perfect",
        "Viewtiful Joe",
        "Wario World"
    ],
    "Mario's Enemies": [
        "Amazing Flyin' Hammer Brother",
        "Ball 'N' Chain",
        "Banzai Bill",
        "Bullet Bill",
        "Buzzy Beetle",
        "Chargin' Chuck",
        "Cheep Cheep",
        "Fishin' Boo",
        "Fishin' Lakitu",
        "Flying Goomba",
        "Jumping Piranha Plant",
        "Green Koopa Troopa",
        "Red Koopa Troopa",
        "Blue Koopa Troopa",
        "Yellow Koopa Troopa",
        "Lava Bubble",
        "Lil Sparky",
        "Mechakoopa",
        "Mega Mole",
        "Sumo Brother",
        "Torpedo Ted",
        "Iggy Koopa",
        "Morton Koopa Jr.",
        "Lemmy Koopa",
        "Ludwig von Koopa",
        "Roy Koopa",
        "Wendy O. Koopa",
        "Larry Koopa",
        "Rocky Wrench"
    ],
    "Zelda Dungeons": [
        "Parapa Palace",
        "Eastern Palace",
        "Desert Palace",
        "Tower of Hera",
        "Palace of Darkness",
        "Swamp Palace",
        "Skull Woods",
        "Thieves' Town",
        "Ice Palace",
        "Misery Mire",
        "Turtle Rock",
        "Ganon's Tower",
        "Tail Cave",
        "Bottle Grotto",
        "Key Cavern",
        "Angler's Tunnel",
        "Catfish's Maw",
        "Face Shrine",
        "Eagle's Tower",
        "Inside the Deku Tree",
        "Dodongo's Cavern",
        "Inside Jabu-Jabu's Belly",
        "Forest Temple",
        "Fire Temple",
        "Ice Cavern",
        "Water Temple",
        "Bottom of the Well",
        "Shadow Temple",
        "Spirit Temple",
        "Woodfall Temple",
        "Snowhead Temple",
        "Great Bay Temple",
        "Stone Tower Temple",
        "Forsaken Fortress",
        "Dragon Roost Cavern",
        "Forbidden Woods",
        "Tower of the Gods",
        "Goron Mines",
        "Lakebed Temple",
        "Arbiter's Grounds",
        "Snowpeak Ruins",
        "Temple of Time",
        "City in the Sky",
        "Palace of Twilight"
    ],
    "Legend of Zelda Items": [
        "Master Sword",
        "Tempered Sword",
        "Golden Sword",
        "Mirror Shield",
        "Magic Hammer",
        "Zora's Flippers",
        "Piece of Heart",
        "Cane of Somaria",
        "Cane of Byrna",
        "Power Glove",
        "Titan's Mitt",
        "Hookshot",
        "Fire Rod",
        "Ice Rod",
        "Pegasus Boots",
        "Roc's Feather",
        "Megaton Hammer",
        "Light Arrow",
        "Deku Leaf",
        "Wind Waker",
        "Tingle Tuner",
        "Iron Boots",
        "Cane of Pacci",
        "Hylian Shield",
        "Gale Boomerang",
        "Double Clawshots",
        "Ball and Chain",
        "Dominion Rod",
        "Gust Bellows"
    ],
    "Minecraft Blocks": [
        "Acacia Button",
        "Acacia Door",
        "Acacia Fence",
        "Acacia Leaves",
        "Acacia Log",
        "Acacia Planks",
        "Acacia Sapling",
        "Acacia Sign",
        "Acacia Slab",
        "Acacia Stairs",
        "Acacia Trapdoor",
        "Acacia Wood",
        "Activator Rail",
        "Ancient Debris",
        "Andesite Slab",
        "Andesite Stairs",
        "Andesite Wall",
        "Azure Bluet",
        "Birch Button",
        "Birch Door",
        "Birch Fence",
        "Birch Leaves",
        "Birch Log",
        "Birch Planks",
        "Birch Sapling",
        "Birch Sign",
        "Birch Slab",
        "Birch Stairs",
        "Birch Trapdoor",
        "Birch Wood",
        "Black Banner",
        "Black Bed",
        "Black Carpet",
        "Black Concrete",
        "Black Wool",
        "Blackstone",
        "Blackstone Slab",
        "Blackstone Wall",
        "Blast Furnace",
        "Block of Coal",
        "Block of Gold",
        "Block of Iron",
        "Block of Quartz",
        "Blue Banner",
        "Blue Carpet",
        "Blue Concrete",
        "Blue Orchid",
        "Blue Terracotta",
        "Blue Wool",
        "Bone Block",
        "Bookshelf",
        "Brain Coral",
        "Brain Coral Fan",
        "Brewing Stand",
        "Brick Slab",
        "Brick Stairs",
        "Brick Wall",
        "Brown Banner",
        "Brown Bed",
        "Brown Carpet",
        "Brown Concrete",
        "Brown Mushroom",
        "Brown Wool",
        "Bubble Column",
        "Bubble Coral",
        "Carved Pumpkin",
        "Chipped Anvil",
        "Chorus Flower",
        "Chorus Plant",
        "Coarse Dirt",
        "Cobblestone",
        "Command Block",
        "Composter",
        "Cornflower",
        "Crafting Table",
        "Creeper Head",
        "Crimson Button",
        "Crimson Door",
        "Crimson Fence",
        "Crimson Fungus",
        "Crimson Hyphae",
        "Crimson Nylium",
        "Crimson Planks",
        "Crimson Roots",
        "Crimson Sign",
        "Crimson Slab",
        "Crimson Stairs",
        "Crimson Stem",
        "Crying Obsidian",
        "Cut Sandstone",
        "Cyan Banner",
        "Cyan Carpet",
        "Cyan Concrete",
        "Cyan Terracotta",
        "Cyan Wool",
        "Damaged Anvil",
        "Dandelion",
        "Dark Oak Button",
        "Dark Oak Door",
        "Dark Oak Fence",
        "Dark Oak Leaves",
        "Dark Oak Log",
        "Dark Oak Planks",
        "Dark Oak Sign",
        "Dark Oak Slab",
        "Dark Oak Stairs",
        "Dark Oak Wood",
        "Dark Prismarine",
        "Dead Bush",
        "Dead Fire Coral",
        "Dead Horn Coral",
        "Dead Tube Coral",
        "Detector Rail",
        "Diamond Ore",
        "Diorite Slab",
        "Diorite Stairs",
        "Diorite Wall",
        "Dispenser",
        "Dragon Egg",
        "Dragon Head",
        "Emerald Ore",
        "End Stone",
        "Ender Chest",
        "Fire Coral",
        "Fire Coral Fan",
        "Fletching Table",
        "Flower Pot",
        "Glass Pane",
        "Glowstone",
        "Granite Slab",
        "Granite Stairs",
        "Granite Wall",
        "Grass Block",
        "Grass Path",
        "Gray Banner",
        "Gray Carpet",
        "Gray Concrete",
        "Gray Terracotta",
        "Gray Wool",
        "Green Banner",
        "Green Bed",
        "Green Carpet",
        "Green Concrete",
        "Green Wool",
        "Grindstone",
        "Honey Block",
        "Honeycomb Block",
        "Horn Coral",
        "Horn Coral Fan",
        "Infested Stone",
        "Iron Bars",
        "Iron Door",
        "Iron Trapdoor",
        "Jack o'Lantern",
        "Jungle Button",
        "Jungle Door",
        "Jungle Fence",
        "Jungle Leaves",
        "Jungle Log",
        "Jungle Planks",
        "Jungle Sapling",
        "Jungle Sign",
        "Jungle Slab",
        "Jungle Stairs",
        "Jungle Trapdoor",
        "Jungle Wood",
        "Large Fern",
        "Light Blue Bed",
        "Light Blue Wool",
        "Light Gray Bed",
        "Light Gray Wool",
        "Lime Banner",
        "Lime Carpet",
        "Lime Concrete",
        "Lime Terracotta",
        "Lime Wool",
        "Lodestone",
        "Magenta Banner",
        "Magenta Bed",
        "Magenta Carpet",
        "Magenta Wool",
        "Magma Block",
        "Mushroom Stem",
        "Nether Bricks",
        "Nether Gold Ore",
        "Nether Sprouts",
        "Nether Wart",
        "Netherrack",
        "Note Block",
        "Oak Button",
        "Oak Fence",
        "Oak Fence Gate",
        "Oak Leaves",
        "Oak Planks",
        "Oak Sapling",
        "Oak Stairs",
        "Oak Trapdoor",
        "Oak Wall Sign",
        "Orange Banner",
        "Orange Bed",
        "Orange Carpet",
        "Orange Concrete",
        "Orange Tulip",
        "Orange Wool",
        "Oxeye Daisy",
        "Packed Ice",
        "Pink Banner",
        "Pink Carpet",
        "Pink Concrete",
        "Pink Terracotta",
        "Pink Tulip",
        "Pink Wool",
        "Player Head",
        "Polished Basalt",
        "Powered Rail",
        "Prismarine",
        "Prismarine Slab",
        "Prismarine Wall",
        "Purple Banner",
        "Purple Bed",
        "Purple Carpet",
        "Purple Concrete",
        "Purple Wool",
        "Purpur Block",
        "Purpur Pillar",
        "Purpur Slab",
        "Purpur Stairs",
        "Quartz Bricks",
        "Quartz Pillar",
        "Quartz Slab",
        "Quartz Stairs",
        "Red Banner",
        "Red Carpet",
        "Red Concrete",
        "Red Mushroom",
        "Red Sandstone",
        "Red Shulker Box",
        "Red Terracotta",
        "Red Tulip",
        "Redstone Lamp",
        "Redstone Ore",
        "Redstone Torch",
        "Respawn Anchor",
        "Rose Bush",
        "Sandstone",
        "Sandstone Slab",
        "Sandstone Wall",
        "Scaffolding",
        "Sea Lantern",
        "Sea Pickle",
        "Shroomlight",
        "Shulker Box",
        "Skeleton Skull",
        "Slime Block",
        "Smithing Table",
        "Smooth Quartz",
        "Smooth Stone",
        "Snow Block",
        "Soul Campfire",
        "Soul Lantern",
        "Soul Torch",
        "Soul Sand",
        "Soul Soil",
        "Spruce Button",
        "Spruce Door",
        "Spruce Fence",
        "Spruce Leaves",
        "Spruce Log",
        "Spruce Planks",
        "Spruce Sapling",
        "Spruce Sign",
        "Spruce Slab",
        "Spruce Stairs",
        "Spruce Trapdoor",
        "Spruce Wood",
        "Sticky Piston",
        "Stone Bricks",
        "Stone Button",
        "Stone Slab",
        "Stone Stairs",
        "Stonecutter",
        "Structure Block",
        "Structure Void",
        "Sugar Cane",
        "Sunflower",
        "Tall Grass",
        "Terracotta",
        "Trapped Chest",
        "Tripwire Hook",
        "Tube Coral",
        "Tube Coral Fan",
        "Turtle Egg",
        "Twisting Vines",
        "Warped Button",
        "Warped Door",
        "Warped Fence",
        "Warped Fungus",
        "Warped Hyphae",
        "Warped Nylium",
        "Warped Planks",
        "Warped Roots",
        "Warped Sign",
        "Warped Slab",
        "Warped Stairs",
        "Warped Stem",
        "Warped Trapdoor",
        "Weeping Vines",
        "Wet Sponge",
        "White Banner",
        "White Bed",
        "White Carpet",
        "White Concrete",
        "White Tulip",
        "White Wool",
        "Wither Rose",
        "Yellow Banner",
        "Yellow Bed",
        "Yellow Carpet",
        "Yellow Concrete",
        "Yellow Wool",
        "Zombie Head"
    ],
    "Team Fortress 2 Weapons": [
        "Air Strike",
        "Ambassador",
        "Axtinguisher",
        "Back Scatter",
        "Back Scratcher",
        "Backburner",
        "Bat Outta Hell",
        "Bazaar Bargain",
        "Blutsauger",
        "Bootlegger",
        "Boston Basher",
        "Brass Beast",
        "Buff Banner",
        "Candy Cane",
        "Chargin' Targe",
        "Cozy Camper",
        "Dead Ringer",
        "Diamondback",
        "Direct Hit",
        "Dragon's Fury",
        "Escape Plan",
        "Eureka Effect",
        "Eviction Notice",
        "Family Business",
        "Fists of Steel",
        "Frying Pan",
        "Gunslinger",
        "Holiday Punch",
        "Holy Mackerel",
        "Homewrecker",
        "Iron Bomber",
        "Loose Cannon",
        "Market Gardener",
        "Pain Train",
        "Panic Attack",
        "Postal Pummeler",
        "Rainblower",
        "Rescue Ranger",
        "Reserve Shooter",
        "Righteous Bison",
        "Rocket Jumper",
        "Scorch Shot",
        "Second Banana",
        "Short Circuit",
        "Soda Popper",
        "Solemn Vow",
        "Splendid Screen",
        "Sticky Jumper",
        "Sun-on-a-Stick",
        "Sydney Sleeper",
        "Syringe Gun",
        "Third Degree",
        "Tide Turner",
        "Vaccinator",
        "Widowmaker"
    ],
    "Super Mario 64 Stars": [
        "Chip Off Whomp's Block",
        "Shoot into the Wild Blue",
        "Mario Wings to the Sky",
        "Blast Away the Wall",
        "Through the Jet Stream",
        "Slip Slidin' Away",
        "Li'l Penguin Lost",
        "Go on a Ghost Hunt",
        "Elevate for 8 Red Coins",
        "Big Penguin Race",
        "Snowman's Lost His Head",
        "Wall Kicks Will Work",
        "Big Boo's Balcony",
        "Watch for Rolling Rocks",
        "Boil the Big Bully",
        "Bully the Bullies",
        "Shining Atop the Pyramid",
        "Board Bowser's Sub",
        "Chests in the Current",
        "Red-Hot Log Rolling",
        "Through the Jet Stream",
        "Pyramid Puzzle",
        "The Manta Ray's Reward",
        "Snowman's Big Head",
        "Chill with the Bully",
        "Shocking Arrow Lifts!",
        "Top o' the Town",
        "Scale the Mountain",
        "In the Deep Freeze",
        "Mysterious Mountainside",
        "Into the Igloo",
        "Go to Town for Red Coins",
        "Pluck the Piranha Flower",
        "Roll into the Cage",
        "The Big House in the Sky",
        "Five Itty Bitty Secrets",
        "Stomp on the Thwomp",
        "Swingin' in the Breeze",
        "Wiggler's Red Coins",
        "Make Wiggler Squirm",
        "Stop Time for Red Coins",
        "Tricky Triangles!"
    ],
    "Mario Kart Tracks": [
        "Airship Fortress",
        "Banshee Boardwalk",
        "Bone-Dry Dunes",
        "Bowser's Castle",
        "Cheep Cheep Beach",
        "Cheese Land",
        "Choco Mountain",
        "Cloudtop Cruise",
        "Coconut Mall",
        "DK's Jungle Parkway",
        "Daisy Cruiser",
        "Delfino Square",
        "Desert Hills",
        "Dolphin Shoals",
        "Dry Dry Desert",
        "Dry Dry Ruins",
        "Electrodrome",
        "Frappe Snowland",
        "Grumble Volcano",
        "Kalimari Desert",
        "Koopa Troopa Beach",
        "Lakeside Park",
        "Luigi Circuit",
        "Luigi Raceway",
        "Luigi's Mansion",
        "Maple Treeway",
        "Mario Circuit",
        "Mario Kart Stadium",
        "Mario Raceway",
        "Moo Moo Farm",
        "Moo Moo Meadows",
        "Mount Wario",
        "Mushroom Bridge",
        "Mushroom City",
        "Mushroom Gorge",
        "Neo Bowser City",
        "Peach Beach",
        "Peach Circuit",
        "Piranha Plant Slide",
        "Rainbow Road",
        "Ribbon Road",
        "Royal Raceway",
        "Sherbet Land",
        "Shy Guy Falls",
        "Sky Garden",
        "Sunshine Airport",
        "Sweet Sweet Canyon",
        "Thwomp Ruins",
        "Tick-Tock Clock",
        "Toad Circuit",
        "Toad Harbor",
        "Toad's Turnpike",
        "Twisted Mansion",
        "Waluigi Pinball",
        "Waluigi Stadium",
        "Wario Colosseum",
        "Wario Stadium",
        "Wario's Gold Mine",
        "Yoshi Circuit",
        "Yoshi Valley",
    ],
    //gen1 pokemon
    
}
