var minigameAnswers = {
    "SNES Games": [
        "Arkanoid",
        "Breath of Fire",
        "Cameltry",
        "Chrono Trigger",
        "Donkey Kong Country",
        "Donkey Kong Country 2: Diddy's Kong Quest",
        "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
        "Dragon Quest",
        "EarthBound",
        "Earthworm Jim",
        "Final Fantasy IV",
        "Frogger",
        "Harvest Moon",
        "Illusion of Gaia",
        "Joe & Mac",
        "John Madden Football '93",
        "Killer Instinct",
        "Kirby Super Star",
        "Kirby's Avalanche",
        "Kirby's Dream Course",
        "The Legend of the Mystical Ninja",
        "The Legend of Zelda: A Link to the Past",
        "Lemmings",
        "The Lost Vikings",
        "Mario Is Missing!",
        "Mario Paint",
        "Mario's Early Years!",
        "Mario's Time Machine",
        "Mega Man 7",
        "Mega Man X",
        "Mickey Mania",
        "Mortal Kombat 3",
        "Pac-Attack",
        "Pilotwings",
        "Secret of Evermore",
        "Secret of Mana",
        "Star Fox",
        "Super Bomberman",
        "Super Double Dragon",
        "Super Mario All-Stars",
        "Super Mario Kart",
        "Super Mario RPG: Legend of the Seven Stars",
        "Super Mario World",
        "Super Metroid",
        "Tecmo Super Bowl",
        "Tetris Attack",
        "Uniracers",
        "Wario's Woods",
        "Where in the World Is Carmen Sandiego?",
        "WWF Super WrestleMania",
        "Yoshi's Cookie",
        "Yoshi's Island",
        "Yoshi's Safari",
        "Zombies Ate My Neighbors"
    ],
    "N64 Games": [
        "1080° Snowboarding",
        "Banjo-Kazooie",
        "Banjo-Tooie",
        "Blast Corps",
        "Bomberman 64",
        "Bomberman 64: The Second Attack",
        "Bomberman Hero",
        "Castlevania",
        "Diddy Kong Racing",
        "Donkey Kong 64",
        "Dr. Mario 64",
        "Duke Nukem 3D",
        "Gex: Enter the Gecko",
        "Glover",
        "Harvest Moon 64",
        "Hey You, Pikachu!",
        "Kirby 64: The Crystal Shards",
        "The Legend of Zelda: Majora's Mask",
        "The Legend of Zelda: Ocarina of Time",
        "Mario Golf",
        "Mario Kart 64",
        "Mario Party",
        "Paper Mario",
        "Paperboy 64",
        "Pilotwings 64",
        "Pokemon Puzzle League",
        "Pokemon Snap",
        "Pokemon Stadium",
        "Quest 64",
        "Space Station Silicon Valley",
        "Star Fox 64",
        "Super Mario 64",
        "Super Smash Bros.",
        "Superman 64",
        "Tetrisphere",
        "Turok: Dinosaur Hunter",
        "Wipeout 64",
        "Yoshi's Story"
    ],
    "GCN Games": [
        "Beyond Good & Evil",
        "Bomberman Generation",
        "Custom Robo",
        "Donkey Kong Jungle Beat",
        "Donkey Konga",
        "Final Fantasy Crystal Chronicles",
        "Gauntlet Dark Legacy",
        "Harvest Moon: A Wonderful Life",
        "James Bond 007: Agent Under Fire",
        "James Bond 007: Everything or Nothing",
        "Kirby Air Ride",
        "The Legend of Zelda: The Wind Waker",
        "The Legend of Zelda: Twilight Princess",
        "Luigi's Mansion",
        "Mario Golf: Toadstool Tour",
        "Mario Kart: Double Dash",
        "Mario Power Tennis",
        "Metroid Prime",
        "Metroid Prime 2: Echoes",
        "Paper Mario: The Thousand-Year Door",
        "Pikmin",
        "Pokémon Colosseum",
        "Sonic Adventure 2 Battle",
        "Star Fox Adventures",
        "Super Mario Strikers",
        "Super Mario Sunshine",
        "Super Monkey Ball",
        "Tales of Symphonia",
        "TimeSplitters: Future Perfect",
        "Viewtiful Joe",
        "Wario World"
    ]
}
