var allLevelsTestData = [
    { code: "0LT-Y30-G2G", maker: "jevarel_UXB_56X-V1N-6JF", title: "Secret of Mana 4.1 #TF", difficulty: 0.5, style: "SMW", tags: ["1 CP", "Music"] },
    { code: "0YB-THL-VVG", maker: "lLucer", title: "Mad Lad's Muncher Mineshaft", difficulty: 0.5, style: "SMB", tags: ["2 CP"] },
    { code: "18B-DCR-RJG", maker: "lLucer", title: "◆ ₽riδε₽σg ωσrlδ: Rεδ ◆", difficulty: 0.5, style: "SMB1", tags: ["1 CP"] },
    { code: "3W0-381-GLF", maker: "Gift", title: "Little Lite Lunar Logs", difficulty: 0.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "4FK-M29-FNG", maker: "Insulin", title: "Barchan", difficulty: 0.5, style: "SMW", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "4PH-21D-PWF", maker: "Link.7od", title: "3DW Links Adventure In 3D Land! #TF", difficulty: 0.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "5D4-MT0-XRF", maker: "Adv_Trash", title: "[SMBAT] 2-♦️Monty Mole Challenge", difficulty: 0.5, style: "SMB", tags: ["0 CP", "Clear Condition"] },
    { code: "5JV-M4J-4VG", maker: "Adv_Trash", title: "[SMBAT] 1-♦️Goomba Challenge", difficulty: 0.5, style: "SMB", tags: ["0 CP", "Clear Condition"] },
    { code: "752-X97-6HF", maker: "MVXgameS", title: "⭐️-⭐️ A (Auto) Fantastik Ending!", difficulty: 0.5, style: "SM3DW", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "8KB-5MG-DPF", maker: "Link.7od", title: "Link Continues His Parkour Path!", difficulty: 0.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "9VC-3V0-L2G", maker: "Èžèkíèł", title: "Spin Jump To The End #TF", difficulty: 0.5, style: "SMW", tags: ["Single Player", "Technical"] },
    { code: "B8H-SJD-GHF", maker: "PCTheWolf", title: "Moleing my way Downtown!", difficulty: 0.5, style: "SMW", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "C7N-HLK-HFG", maker: "MVXgameS", title: "⭐️-1 Very Appreciative Kaizo #TF", difficulty: 0.5, style: "SM3DW", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "C9T-56N-HFG", maker: "Vico", title: "The E Teleport to the description", difficulty: 0.5, style: "SMB3", tags: ["1 CP"] },
    { code: "D95-Y5M-HWG", maker: "Link.7od", title: "Time To Escape The Parkour Cave!", difficulty: 0.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "F4C-T4H-6WF", maker: "lLucer", title: "● ₽ridε₽σg ωσrlδ: σrαηgε ●", difficulty: 0.5, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "F7J-YX2-C1G", maker: "Link.7od", title: "★Link Enters The Parkour Desert★", difficulty: 0.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "FLQ-1MP-FWG", maker: "Boops", title: "Boops Short - Blissful Blue", difficulty: 0.5, style: "SMB1", tags: ["Short and sweet", "Single player"] },
    { code: "RC0-TK5-5MF", maker: "Èžèkíèł", title: "Castle of Shells #TF", difficulty: 0.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "S0J-8FT-QLF", maker: "Insulin", title: "Thwomp Ruins", difficulty: 0.5, style: "SMB", tags: ["Clear Condition"] },
    { code: "TGW-JX9-NRF", maker: "Boops", title: "Boops Short - Delicate Dunes", difficulty: 0.5, style: "SMB3", tags: ["Short and sweet", "Single player"] },
    { code: "WG0-KJB-2PF", maker: "Link.7od", title: "★Big Jelly's Kaizo Adventure★", difficulty: 0.5, style: "SMB3", tags: ["1 CP"] },
    { code: "0SB-DK7-0YG", maker: "Kactus", title: "Dingus Level", difficulty: 1, style: "SMB", tags: ["Short & Sweet"] },
    { code: "1L7-JF0-3TG", maker: "pasjevw88", title: "## Fantastik Jampin' Munchers ##", difficulty: 1, style: "SMW", tags: ["Short and sweet", "Technical"] },
    { code: "20D-WKP-2RG", maker: "Èžèkíèł", title: "This is a lvl with no name #TF", difficulty: 1, style: "NSMBU", tags: ["Single player", "Technical"] },
    { code: "286-0JG-40H", maker: "Drain79", title: "Finding Oasis #TMR", difficulty: 1, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "2D2-7P0-Y8G", maker: "pasjevw88", title: "MW Platforms:NSMBU Hungry Valley", difficulty: 1, style: "NSMBU", tags: ["Technical", "Themed"] },
    { code: "519-Q0C-RGG", maker: "Nelesio", title: "SNW Omega: Night time cap #TF", difficulty: 1, style: "SMW", tags: ["Short & Sweet"] },
    { code: "5QC-64K-P8G", maker: "HighLow", title: "Brief Brat Bouncing #TF", difficulty: 1, style: "SMB3", tags: ["0 CP", "Short & Sweet"] },
    { code: "6FH-445-BSF", maker: "RainbowJaymee", title: "JZL Goes to Wiggler's Town #TF", difficulty: 1, style: "SMB", tags: ["1 CP"] },
    { code: "6JC-K0N-TLF", maker: "AMMondMilk", title: "Planet No-put-foot", difficulty: 1, style: "SMW", tags: ["0 CP"] },
    { code: "9ND-CKL-W0H", maker: "Boops", title: "Boopity Bawp", difficulty: 1, style: "SMW", tags: ["Short and sweet", "Single player"] },
    { code: "9R5-7XT-CYG", maker: "KingJ0804", title: "Castle in the Sky", difficulty: 1, style: "SMB3", tags: ["1 CP"] },
    { code: "CJ7-N75-KYG", maker: "Fatality", title: "1-1: A Good Stompin", difficulty: 1, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "CTD-J68-YJG", maker: "lLucer", title: "₽riδε₽σg ωσrlδ: ₽υrpιε", difficulty: 1, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "CXF-JPW-D0G", maker: "Tic_y", title: "Coaster Toaster & Freezer Breeze", difficulty: 1, style: "SMB", tags: ["1 CP"] },
    { code: "F0M-280-XLF", maker: "JewMstr87", title: "Journey To Mushroom Kingdom", difficulty: 1, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "FGX-13X-XLF", maker: "Boops", title: "Boops Short - Donut Dancing", difficulty: 1, style: "SMW", tags: ["Short and sweet", "Single player"] },
    { code: "FNG-565-5MF", maker: "CB", title: "The Desert Of Moles", difficulty: 1, style: "SMB", tags: ["0 CP", "Short & Sweet"] },
    { code: "G05-KMX-NVF", maker: "psycotyca", title: "Mega Man 2: Air Man Stage", difficulty: 1, style: "SMB3", tags: ["0 CP"] },
    { code: "G6N-CY0-YJF", maker: "LeeRetro_maker", title: "± Ilopango Lake 2 ± #TJ #TF", difficulty: 1, style: "NSMBU", tags: ["Single player", "Technical"] },
    { code: "GXP-G5X-RSF", maker: "lLucer", title: "Château de Grenouille Nocturne", difficulty: 1, style: "SMB3", tags: ["Autoscroll", "Themed"] },
    { code: "H88-1BQ-B1H", maker: "Nelesio", title: "SNW Omega: Autumnal Sky", difficulty: 1, style: "NSMBU", tags: ["1 CP"] },
    { code: "HPS-L0T-WPF", maker: "Link.7od", title: "The Z Jump Master! #TF #TJ #TZ", difficulty: 1, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "HTS-Y4N-CGG", maker: "Tic_y", title: "Thwomp Paradise #TJ #TF", difficulty: 1, style: "SMB3", tags: ["0 CP", "Short & Sweet"] },
    { code: "K0Q-V97-BTG", maker: "JewMstr87", title: "Miami's Platforming Fortress", difficulty: 1, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "L44-2B7-LKG", maker: "pasjevw88", title: "MW Platforms: SMB1 Hungry Valley", difficulty: 1, style: "SMB", tags: ["Technical", "Themed"] },
    { code: "L6N-DL5-KSG", maker: "lLucer", title: "In the Hall of the Muncher King", difficulty: 1, style: "SMB", tags: ["2 CP"] },
    { code: "L8R-37V-02H", maker: "Gift", title: "Air Acrobatics | #TF #FS", difficulty: 1, style: "SMW", tags: ["1 CP", "Contest", "FS II", "Short & Sweet"] },
    { code: "LB6-46K-JSF", maker: "lLucer", title: "Lonk's Platform Palace", difficulty: 1, style: "SMB", tags: ["2 CP"] },
    { code: "LGH-T85-RFF", maker: "JewMstr87", title: "Return to Mushroom Kingdom", difficulty: 1, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "MGS-QTJ-DMG", maker: "Boops", title: "6 Years Of Booping Around!", difficulty: 1, style: "SMW", tags: ["1 CP"] },
    { code: "MXK-FGY-VTG", maker: "SuperBeastGN", title: "The Dark Night Returns", difficulty: 1, style: "SMB", tags: ["2 CP"] },
    { code: "N9D-MRT-9MF", maker: "pasjevw88", title: "MW Platforms: SMB2 Hungry Valley", difficulty: 1, style: "SMB", tags: ["Technical", "Themed"] },
    { code: "PBJ-RLH-1WG", maker: "lLucer", title: "◆ ₽riδε₽σg ωσrld: γεllσω ◆", difficulty: 1, style: "NSMBU", tags: ["Single player", "Technical"] },
    { code: "PCL-BNM-TGG", maker: "NonBasicChaos", title: "Satisfied Spelunking #TF", difficulty: 1, style: "SMB", tags: ["2 CP"] },
    { code: "PSK-V3N-HDF", maker: "jevarel_UXB_56X-V1N-6JF", title: "No Shells please. We're British.", difficulty: 1, style: "SMB1", tags: ["Contest", "FS V"] },
    { code: "QJ7-9L9-L6G", maker: "pasjevw88", title: "MW Platforms: SMW Hungry Valley", difficulty: 1, style: "SMW", tags: ["Technical", "Themed"] },
    { code: "R55-YMX-WNG", maker: "lLucer", title: "◎ ₽riδε₽σg ωσrlδ: βluε ◎", difficulty: 1, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "RN2-44T-NGF", maker: "lLucer", title: "Big Boi Jamping: Fragile Floor", difficulty: 1, style: "SMB", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "RQK-593-QLF", maker: "Link.7od", title: "★Link Becomes The King Of Kaizo★", difficulty: 1, style: "SMW", tags: ["1 CP"] },
    { code: "RR2-1JV-P0H", maker: "RainbowJaymee", title: "Brick Against the Wall #TF", difficulty: 1, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "SW3-7GX-QHG", maker: "Link.7od", title: "Links Rom Hack Level! #FS #TF", difficulty: 1, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "T1X-G4B-P8G", maker: "lLucer", title: "The Toad's Frostbitten Villa", difficulty: 1, style: "SMB3", tags: ["2 CP"] },
    { code: "V0K-CT1-G7G", maker: "HighLow", title: "⌒ Beware the Bloopa Troopa ⌒ #TF", difficulty: 1, style: "SMB", tags: ["1 CP"] },
    { code: "WHK-7J5-VWG", maker: "lLucer", title: "■ ₽riδε₽σg ωσrlδ: Grεεη ■", difficulty: 1, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "WK4-L5K-JFF", maker: "Drain79", title: "Castle Mixer 2022 #TF", difficulty: 1, style: "SMB1", tags: ["Contest"] },
    { code: "WNY-N7B-Q0H", maker: "ShoeGoomba", title: "If the Shoe Fits", difficulty: 1, style: "SMB3", tags: ["1 CP", "Contest", "FS III"] },
    { code: "WR7-6FL-JPF", maker: "RainbowJaymee", title: "Waluigi Gucci Boots #TF", difficulty: 1, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "XP3-C3S-SLG", maker: "Dr.Popples", title: "• Peanut Butter Bridge • #TF 1-1", difficulty: 1, style: "SMB3", tags: ["1 CP"] },
    { code: "Y3X-QDG-HWF", maker: "RainbowJaymee", title: "Super Fantastik Bros 2 #TF", difficulty: 1, style: "SMB", tags: ["2 CP"] },
    { code: "YL6-1SJ-LKF", maker: "pasjevw88", title: "☆★Sky Full of Spiny's★☆", difficulty: 1, style: "SMW", tags: ["Short and sweet", "Technical"] },
    { code: "YR2-NSX-3PG", maker: "RainbowJaymee", title: "The Legend Of Zeldor #TF #TN", difficulty: 1, style: "SMB", tags: ["2 CP", "Link"] },
    { code: "06Y-VHG-W1H", maker: "RainbowJaymee", title: "Gravyard Shift 2 #TF", difficulty: 1.5, style: "SMW", tags: ["2 CP"] },
    { code: "09J-7XF-9TG", maker: "PhoenixNL", title: "Galactic Shellventure", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "0PS-DLT-B1H", maker: "PhoenixNL", title: "Beckys trithwompant Return", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "0TJ-7SB-T9G", maker: "BeefLegend", title: "Snowy Shells", difficulty: 1.5, style: "SMB3", tags: ["0 CP", "Short & Sweet"] },
    { code: "1DX-QDT-6NG", maker: "Tic_y", title: "Αeriality #TF", difficulty: 1.5, style: "SMW", tags: ["Standard", "Themed"] },
    { code: "2K8-MVY-TBG", maker: "DragnHntr", title: "Shells Solemnly Suspended", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "2X3-GYS-PGG", maker: "HighLow", title: "◇Precarious Parkour Playroom◇", difficulty: 1.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "3K6-NHC-RHF", maker: "HighLow", title: "«Children of Koopa» #TF #FS ", difficulty: 1.5, style: "SMB3", tags: ["Contest", "FS V"] },
    { code: "42N-F62-NHG", maker: "defman144", title: "1-4 Kalahari Hot Springs", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "4BV-4YL-TSF", maker: "HighLow", title: "The Invincible Dreadnought #TF", difficulty: 1.5, style: "SMB3", tags: ["2 CP"] },
    { code: "4FC-69F-2NF", maker: "Adv_Trash", title: "[SMBAT] 6-♦️ Boo Challenge", difficulty: 1.5, style: "SMB", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "4Q8-N7S-HDG", maker: "defman144", title: "C-1 Bilago's Salt Mine", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "51M-17Y-3RF", maker: "lLucer", title: "SLW 1-3ーLaws of Aviation", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "572-9DC-21H", maker: "PhoenixNL", title: "Bouncy Valley", difficulty: 1.5, style: "SMB3", tags: ["0 CP", "Short & Sweet"] },
    { code: "5G6-KKV-PHG", maker: "RainbowJaymee", title: "100% Canadian Bacon #TF", difficulty: 1.5, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "6JX-SXR-65G", maker: "Boops", title: "Can I take you to pROM? #TF #FS", difficulty: 1.5, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "6KP-8C2-7YG", maker: "RainbowJaymee", title: "Secret Tetris Level #TF", difficulty: 1.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "7CD-FWN-DMG", maker: "Boops", title: "Shell Throw 420", difficulty: 1.5, style: "SMW", tags: ["Short and sweet", "Single player"] },
    { code: "7M0-F53-GYF", maker: "Nelesio", title: "SNW Ω: Spinning on stuff", difficulty: 1.5, style: "SMW", tags: ["Short and sweet", "Single player"] },
    { code: "886-M90-W4G", maker: "HighLow", title: "Cosmic Caverns #TF", difficulty: 1.5, style: "SMB3", tags: ["2 CP"] },
    { code: "93H-F0X-MVF", maker: "RainbowJaymee", title: "Speedy Reclaimez #TF", difficulty: 1.5, style: "SMB", tags: ["0 CP", "Short & Sweet"] },
    { code: "95L-J14-SCG", maker: "PhoenixNL", title: "Chateau Scarabee", difficulty: 1.5, style: "SMW", tags: ["0 CP"] },
    { code: "9BB-YDJ-KFG", maker: "Dr.Popples", title: "▼HighLow's Acquiescent Pyramids▼", difficulty: 1.5, style: "SMB3", tags: ["1 CP"] },
    { code: "9DN-WX9-KQG", maker: "Drain79", title: "Winter Coin Expedition #TJ", difficulty: 1.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "9T2-TJ2-QCG", maker: "HighLow", title: "Busy Body Buzzy #TF", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "9VC-Y5K-RNF", maker: "Martin", title: "The ΦΜЭИ: Resurrected #TF", difficulty: 1.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "B8P-CQM-4TF", maker: "gdashfan13", title: "Vine forest shells #TF #TS", difficulty: 1.5, style: "SMW", tags: ["2 CP"] },
    { code: "BQP-3TY-DRF", maker: "Fer", title: "● Icing Sugar ●", difficulty: 1.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet", "Technical", "Themed"] },
    { code: "CJC-L34-HDF", maker: "Nelesio", title: "SNW Omega: Shortcake #TF", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "CSF-9WQ-HSF", maker: "RainbowJaymee", title: "Scary Waters #TF", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "F1C-JGQ-VPF", maker: "KingJ0804", title: "Shells in the Sky", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "FCV-73J-M5G", maker: "Nelesio", title: "SNW Omega: Wiggle, wiggle ...", difficulty: 1.5, style: "SMB", tags: ["Short & Sweet"] },
    { code: "FG3-CMK-QRG", maker: "Za_gZi_gz31", title: "Old man Jankins", difficulty: 1.5, style: "SM3DW", tags: ["1 CP"] },
    { code: "FLD-GLJ-F2H", maker: "JewMstr87", title: "Thwomp Attack 2-Thwomps Revenge", difficulty: 1.5, style: "NSMBU", tags: ["2 CP", "Single Player", "Technical"] },
    { code: "FSK-7NT-HMG", maker: "Drain79", title: "Plumber Trouble #TF", difficulty: 1.5, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "G41-QTF-BMG", maker: "Dr.Popples", title: "Wait There Was a Contest?", difficulty: 1.5, style: "SM3DW", tags: ["Contest"] },
    { code: "G9K-CDN-DQG", maker: "HighLow", title: "Chomp Chomp Mr. Thwomp #FS #TF", difficulty: 1.5, style: "SMB3", tags: ["1 CP", "Contest", "FS IV"] },
    { code: "GHL-62L-8MF", maker: "Nelesio", title: "SNW: Piranhaland midnight tour", difficulty: 1.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "GJX-RH7-RMF", maker: "HighLow", title: "Iggy's Cargo Armada #TF", difficulty: 1.5, style: "SMW", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "H46-P04-SWF", maker: "lLucer", title: "SLW 1-1ーPlacid Pipe Platforming", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "H56-WPD-3FG", maker: "HighLow", title: "Larry's Lunar Lair #TF", difficulty: 1.5, style: "SMB3", tags: ["0 CP", "Clear Condition"] },
    { code: "HF2-14P-5YF", maker: "1111111", title: "Playing with tha Boos #TF", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "JHC-5DW-5LG", maker: "HighLow", title: "«Spacestation Phoenix» #TF", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "JJV-G6V-PBG", maker: "RainbowJaymee", title: "Chill Levels Only #teamfantastik", difficulty: 1.5, style: "SM3DW", tags: ["2 CP"] },
    { code: "JVY-9DG-B1G", maker: "SaucePowder", title: "Golden Boy", difficulty: 1.5, style: "SMB", tags: ["0 CP"] },
    { code: "JYN-SY9-WXF", maker: "bilago", title: "Power-Up Platform Peril", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "KGY-XBR-5PG", maker: "JewMstr87", title: "Thwomp Attack", difficulty: 1.5, style: "NSMBU", tags: ["Single player", "Standard"] },
    { code: "KHW-906-FLG", maker: "HighLow", title: "Throne of the Thwomps #TF", difficulty: 1.5, style: "SMB3", tags: ["2 CP"] },
    { code: "KV0-P67-XQG", maker: "defman144", title: "Bone Smugglerz Inc.", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "LL9-W75-6WG", maker: "Èžèkíèł", title: "Purple Jelly Haze #TF", difficulty: 1.5, style: "SMW", tags: ["0 CP"] },
    { code: "MKN-5K4-G9G", maker: "defman144", title: "goombaJAM", difficulty: 1.5, style: "SMB3", tags: ["Single Player", "Technical"] },
    { code: "MMY-CGG-W0H", maker: "Verwalter", title: "Feuchtmoons little Challenge #TF", difficulty: 1.5, style: "SM3DW", tags: ["0 CP"] },
    { code: "MP5-HRK-6CG", maker: "Link.7od", title: "Time Attack Kaizo Style! #TF #FS", difficulty: 1.5, style: "SMW", tags: ["0 CP", "Contest", "FS I", "Short & Sweet"] },
    { code: "N0T-0TB-NLF", maker: "gdashfan13", title: "Koopa's pipeline forest #TF #TS", difficulty: 1.5, style: "SMB3", tags: ["2 CP"] },
    { code: "N64-GX1-YQG", maker: "PhoenixNL", title: "Frozen Vineyard #TF", difficulty: 1.5, style: "SM3DW", tags: ["Single player", "Themed"] },
    { code: "NPV-WWB-WKF", maker: "Èžèkíèł", title: "the forest of death", difficulty: 1.5, style: "SMW", tags: ["Short & Sweet", "Technical"] },
    { code: "NTR-50G-0NG", maker: "Quacken", title: "Galoomba Keep", difficulty: 1.5, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "P1K-GCX-KPG", maker: "Fatality", title: "◇Mysterious Marsh◇", difficulty: 1.5, style: "SMB", tags: ["0 CP", "Short & Sweet"] },
    { code: "P2K-VRN-3PG", maker: "PhoenixNL", title: "Ashgray Cavern#Team Fantastik", difficulty: 1.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "P2X-C28-PQF", maker: "SophieG∞", title: "☆Travesía por el cielo☆ #TF #TS ", difficulty: 1.5, style: "SMW", tags: ["Technical", "Themed"] },
    { code: "P4T-MML-QWG", maker: "RainbowJaymee", title: "Snwbear Fantastik Kaizo Lite #TF", difficulty: 1.5, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "PL6-6HS-C3G", maker: "AMMondMilk", title: "The Jewish Alliance: Part 1", difficulty: 1.5, style: "SMW", tags: ["Single player", "Standard"] },
    { code: "PTY-DBN-KMG", maker: "gdashfan13", title: "Skyjamp tower #TJ #TF", difficulty: 1.5, style: "SMB", tags: ["2 CP"] },
    { code: "QR0-QCL-3XF", maker: "Garchomp", title: "Platforming with ludwig #TF", difficulty: 1.5, style: "SMB3", tags: ["1 CP"] },
    { code: "R1V-PQH-L2G", maker: "HighLow", title: "☆★A Shellish Desert★☆ #TF", difficulty: 1.5, style: "SMB3", tags: ["2 CP"] },
    { code: "R4G-SCX-CTF", maker: "Dr.Popples", title: "Amphibia #TF #FS #TN #TB", difficulty: 1.5, style: "SMB3", tags: ["1 CP", "Contest", "FS III", "Puzzle-solving", "Themed"] },
    { code: "RTL-30S-KTG", maker: "HighLow", title: "The Forest of Whoa! #TF", difficulty: 1.5, style: "SMW", tags: ["2 CP"] },
    { code: "S74-B0M-DJF", maker: "HighLow", title: "The Purple Stuff #TF", difficulty: 1.5, style: "SMW", tags: ["Technical"] },
    { code: "SGN-F52-PSF", maker: "bigj3llygaming", title: "Eerie Cottage Agony #TF #BJG", difficulty: 1.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "SR7-VS7-CFF", maker: "defman144", title: "Living the High&Low Life", difficulty: 1.5, style: "SMB3", tags: ["0 CP", "Short & Sweet"] },
    { code: "TSV-16P-CGG", maker: "JewMstr87", title: "Moles In The Sky", difficulty: 1.5, style: "SMB3", tags: ["Contest", "FS V"] },
    { code: "V7W-NR1-5PG", maker: "defman144", title: "1-3 Mayonnaise Soup", difficulty: 1.5, style: "SMW", tags: ["0 CP"] },
    { code: "VBW-HF6-2RG", maker: "ShoeGoomba", title: "Bowser Jr.'s Bomber Wing #TF #FS", difficulty: 1.5, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "VL0-6M8-YNF", maker: "feo2", title: "The one that got away v2 #TF", difficulty: 1.5, style: "SMW", tags: ["2 CP"] },
    { code: "VQP-9WR-YWF", maker: "SaucePowder", title: "diZZy | #TeamFantastik", difficulty: 1.5, style: "SMW", tags: ["Single Player", "Technical"] },
    { code: "VVT-0VF-MFG", maker: "defman144", title: "con(test) air", difficulty: 1.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "W1D-N0G-5GF", maker: "pasjevw88", title: "Overgrown Muncher House #TJ #TF", difficulty: 1.5, style: "NSMBU", tags: ["Short and sweet", "Technical"] },
    { code: "W2G-17L-YVG", maker: "Fatality", title: "◇Perilous Plantlife◇", difficulty: 1.5, style: "SMB", tags: ["1 CP"] },
    { code: "WMT-0Y0-RMF", maker: "RainbowJaymee", title: "Hot Castle #TF", difficulty: 1.5, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "X7B-BHL-JLF", maker: "PhoenixNL", title: "Stacked Shell Castle", difficulty: 1.5, style: "SMB", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "XHK-CJS-NTF", maker: "pasjevw88", title: "MW Platforms: SMB3 Hungry Valley", difficulty: 1.5, style: "SMB3", tags: ["Technical", "Themed"] },
    { code: "XHS-KJJ-MFF", maker: "ShoeGoomba", title: "Munchers and Pipes #TF", difficulty: 1.5, style: "SMB3", tags: ["1 CP"] },
    { code: "XSG-66P-R0H", maker: "Adv_Trash", title: "Green Grass And Shellin' [Kaizo]", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "Y99-KR8-MFF", maker: "lLucer", title: "SLW 1-2ーValley of the Claws", difficulty: 1.5, style: "SMW", tags: ["1 CP"] },
    { code: "YDM-P03-N5G", maker: "lLucer", title: "Sυbterrαηεαη ₽lαtfσrm βεlτ", difficulty: 1.5, style: "SMW", tags: ["Single player", "Themed"] },
    { code: "YGC-1WF-LLG", maker: "MVXgameS", title: "1-1 Bouncy Bom-omb Beginnings!", difficulty: 1.5, style: "SMB3", tags: ["0 CP", "Clear Condition"] },
    { code: "YPM-HTG-RTF", maker: "Fatality", title: "1-2: Monty Mole's Gold Mine", difficulty: 1.5, style: "SMB3", tags: ["0 CP", "Short & Sweet"] },
    { code: "1MF-YF9-5XG", maker: "RainbowJaymee", title: "Mike is Lost Tonight #TN #TF", difficulty: 2, style: "SMB", tags: ["2 CP"] },
    { code: "1NB-W4F-X3G", maker: "lLucer", title: "The Rotary Sequel", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "1Q4-L4K-PVG", maker: "KamikazeCarl", title: "Kameks Kaizo Castle #FS", difficulty: 2, style: "SMW", tags: ["1 CP", "Contest", "FS I", "Themed"] },
    { code: "2D0-N8N-VGF", maker: "SaucePowder", title: "Defman’s Day Out | #TF", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "2YJ-V70-JGG", maker: "lLucer", title: "SLW 2-3ーChilled Cranium Cabin", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "37G-7XW-5YG", maker: "MVXgameS", title: "2-C Morton’s Highway To Heck", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "3H9-860-CSF", maker: "lLucer", title: "Legion of Cannon and Snow", difficulty: 2, style: "SMW", tags: ["1 CP", "Contest", "FS V", "Single Player"] },
    { code: "3P4-SGR-XRG", maker: "NonBasicChaos", title: "On Track For Success #TF", difficulty: 2, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "3VJ-5K6-QBG", maker: "RainbowJaymee", title: "Mario Goes to the Moon #TF #FS", difficulty: 2, style: "SMW", tags: ["2 CP", "Contest", "FS III"] },
    { code: "40H-FK9-BBG", maker: "PhoenixNL", title: "Frosty Fire", difficulty: 2, style: "SMB", tags: ["0 CP"] },
    { code: "45M-L4W-M4G", maker: "defman144", title: "Acid Romance", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "4MF-1VQ-NXG", maker: "Fer", title: "Vanilla Rocky Road #TJ #TF", difficulty: 2, style: "SMW", tags: ["0 CP", "Technical"] },
    { code: "4R7-MYD-7NG", maker: "PhoenixNL", title: "Flight of the Phoenix", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "4TP-4TQ-NNF", maker: "Tic_y", title: "Chill", difficulty: 2, style: "SMW", tags: ["1 CP", "Music"] },
    { code: "64G-23M-JBG", maker: "gdashfan13", title: "Cotton shell haven #TF", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "67Q-MTY-58G", maker: "lLucer", title: "SLW 2-2ーSliabh Sneachta", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "7T3-T52-0GG", maker: "Fer", title: "Blue Iceberg ", difficulty: 2, style: "SMW", tags: ["0 CP", "Shooter", "Single Player", "Technical"] },
    { code: "7W7-Y7W-4QG", maker: "MVXgameS", title: "Larry’s THICC Boom #TF", difficulty: 2, style: "SMB", tags: ["0 CP", "Clear Condition"] },
    { code: "8P4-KC6-QPF", maker: "Gift", title: "Duck & Cover | #TF", difficulty: 2, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "9Q9-5TR-82G", maker: "pasjevw88", title: "Buzzy Beetle Bounce House #TF", difficulty: 2, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "B6V-LG4-0PF", maker: "Dahweirdacus", title: "Munchtop Woods #TF", difficulty: 2, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "BGC-2QC-4XF", maker: "JewMstr87", title: "SMB1 Goomba’s Toxic Swamp 2", difficulty: 2, style: "SMB", tags: ["2 CP"] },
    { code: "CQV-DKX-FJF", maker: "HighLow", title: "Xtreme Sewer Surfing #TF", difficulty: 2, style: "SMB3", tags: ["1 CP", "Themed"] },
    { code: "CXK-4SL-HKG", maker: "lLucer", title: "SLW 2-1ーStepping Snows", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "D66-JR4-61G", maker: "realbchin", title: "Tardy Brewski #FS #TF", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "DN8-055-PDG", maker: "bigj3llygaming", title: "Hot Foxglove Sip #TF #BJG", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "DPD-RY0-GRF", maker: "Keenzzz", title: "Deadly Combination", difficulty: 2, style: "SMW", tags: ["Single Player"] },
    { code: "FDW-9FC-CWF", maker: "Rogervalo", title: "Winds of winter #TJ #TF", difficulty: 2, style: "SMB1", tags: ["2 CP"] },
    { code: "FJ5-WBX-0VG", maker: "PhoenixNL", title: "Thorny Oasis #TF", difficulty: 2, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "FJ7-BWP-0QG", maker: "RainbowJaymee", title: "Speed Demon #TF", difficulty: 2, style: "SM3DW", tags: ["0 CP", "Single Player", "Speedrun"] },
    { code: "FR6-LCQ-9GG", maker: "lLucer", title: "SLW 1-CーFlight of the Goombud", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "FYT-VCG-J2G", maker: "Boops", title: "Boops in 3D!", difficulty: 2, style: "SM3DW", tags: ["0 CP", "Clear Condition"] },
    { code: "GJT-753-T2G", maker: "JewMstr87", title: "SMW Defman’s Haunted Adventure", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "H57-HS4-J2G", maker: "JewMstr87", title: "Return to Wendys Frozen Fortress", difficulty: 2, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "H5N-L3Y-8MF", maker: "ShoeGoomba", title: "Magma Displacement #TF #TJ", difficulty: 2, style: "SMB3", tags: ["1 CP"] },
    { code: "H9L-B8T-06G", maker: "Quacken", title: "☆ Spike Top Tundra ☆", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "HD0-L3F-N4G", maker: "DragnHntr", title: "Go Dash! Fantastic!", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "JMW-LMP-H1G", maker: "Crystal", title: "A short Hike through the Bramble", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "JP6-1DC-X4G", maker: "bundcord", title: "reflecting marsh", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "JW2-5T7-JVG", maker: "Hanzo", title: "-[Shots Fired]- [TF]", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "K6Y-2VJ-XBG", maker: "KingJ0804", title: "Shells in the Snow", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "KBH-NW6-SDF", maker: "JewMstr87", title: "Wrath of the Thwomp ", difficulty: 2, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "KK0-FHF-BKF", maker: "MVXgameS", title: "3-3 Boo’s Quicksand Sandshells!", difficulty: 2, style: "SMB", tags: ["1 CP"] },
    { code: "KX5-F5F-KWG", maker: "The", title: "18^2", difficulty: 2, style: "SMW", tags: ["2 CP", "Contest", "FS I"] },
    { code: "KX9-TL3-XNG", maker: "MVXgameS", title: "1-3 Green Skull Runway #TF", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "LVM-VTF-3FF", maker: "Dobbs", title: "Hover Cat Kitchen", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "MYM-NHK-GHF", maker: "Quacken", title: "Surfin' on Scaffolding #TF", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "N2X-PCN-JRF", maker: "Quacken", title: "Chomping at the Bit #FS", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "NDM-DX7-2LF", maker: "RainbowJaymee", title: "Nuclear Explosion #TF #TN", difficulty: 2, style: "SMW", tags: ["Technical"] },
    { code: "NJ9-SCJ-7XG", maker: "Toastax", title: "Golden Greetings #TF", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "P53-LKX-HHG", maker: "Adv_Trash", title: "1-1 Plain Hill Heights [Kaizo]", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "PN1-M1F-GWF", maker: "Y0gamer", title: "The End of Teamshell", difficulty: 2, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "PSM-C9M-MHG", maker: "RainbowJaymee", title: "Cambell Tomato Sup #TF", difficulty: 2, style: "NSMBU", tags: ["Single player", "Technical"] },
    { code: "PVQ-S3W-MSG", maker: "NonBasicChaos", title: "Saws , Spikes and Shenanigans", difficulty: 2, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "PXK-Y96-R8G", maker: "RainbowJaymee", title: "The Running Frog #TF", difficulty: 2, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "Q1F-X44-G0H", maker: "MVXgameS", title: "Bowser-C Bowsers Fire Flame Run!", difficulty: 2, style: "NSMBU", tags: ["Clear Condition"] },
    { code: "Q5P-38Y-VLG", maker: "PhoenixNL", title: "Romtastik Adventure", difficulty: 2, style: "SMB", tags: ["0 CP"] },
    { code: "QDW-QPX-1YF", maker: "RainbowJaymee", title: "Olympic Kaizo #TF", difficulty: 2, style: "SMW", tags: ["2 CP"] },
    { code: "QGS-GJC-JJF", maker: "OGZINHO", title: "Ambitionz Az A Ridah #TF", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "QJL-5LD-TNF", maker: "HighLow", title: "«Secret of the Ooze» #TF", difficulty: 2, style: "SMB", tags: ["0 CP", "Short & Sweet"] },
    { code: "R1H-C3J-QMG", maker: "RainbowJaymee", title: "Wizard Blizzard Lizard #TF #FS", difficulty: 2, style: "NSMBU", tags: ["Contest", "FS V"] },
    { code: "R1L-FVJ-H5G", maker: "PhoenixNL", title: "Goomba Space #TF", difficulty: 2, style: "SMW", tags: ["0 CP", "Clear Condition"] },
    { code: "R5D-R94-FKG", maker: "MVXgameS", title: "2-1 Abandoned Koopa Cavern #TF", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "RRD-L85-0DG", maker: "HighLow", title: "◇Piranha◇Pipe◇Plaza◇ #TF", difficulty: 2, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "RTC-KXW-7CG", maker: "PorkSweater", title: "Super Easy Link Level? #TEAMS", difficulty: 2, style: "SMB1", tags: ["Single player", "Themed"] },
    { code: "RYF-3HQ-BQG", maker: "SaucePowder", title: "Holding On", difficulty: 2, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "S13-P7J-9QG", maker: "JurassicLucas", title: "Koopa Playground #TF", difficulty: 2, style: "SMW", tags: ["Short and sweet", "Standard"] },
    { code: "S2K-JKK-C2H", maker: "Insulin", title: "Tempest #TS #TF", difficulty: 2, style: "SM3DW", tags: ["Short & Sweet"] },
    { code: "S7J-NG1-SSG", maker: "RainbowJaymee", title: "Frozen Vegetables #TF", difficulty: 2, style: "SMB", tags: ["0 CP"] },
    { code: "SWH-YGN-VSG", maker: "Bald_ridge", title: "I met them in TJ", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "T8G-5YC-54G", maker: "JewMstr87", title: "The Jewish Alliance: Part 2", difficulty: 2, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "TD7-PBT-J2G", maker: "Boops", title: "Rise of Boops: Ghostly Grandeur", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "TGQ-4Q7-BPG", maker: "MVXgameS", title: "3-1 The Railway Ruins #TF", difficulty: 2, style: "SMB", tags: ["1 CP"] },
    { code: "TPX-HPW-41G", maker: "youcandoeet", title: "Platformer-Sawrus #TF", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "TXL-XDS-H4G", maker: "Apo", title: "Bombs n' Stuff #TF", difficulty: 2, style: "SMW", tags: ["Technical", "Themed"] },
    { code: "TYD-YWD-JSF", maker: "Dr.Popples", title: "Calm Before The Storm", difficulty: 2, style: "SMB3", tags: ["2 CP"] },
    { code: "V3F-N25-WKG", maker: "MVXgameS", title: "4-1 Glacial Grove Groove #TF", difficulty: 2, style: "NSMBU", tags: ["Clear Condition"] },
    { code: "VD7-HWM-SQF", maker: "Adv_Trash", title: "Fantastik Desert Vacation #TF", difficulty: 2, style: "SMW", tags: ["1 CP", "Contest", "FS II", "Themed"] },
    { code: "VXT-VBH-KDF", maker: "tflynnie25", title: "Green Vengeance Kaizo #TF", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "VY2-S48-3MF", maker: "Garchomp", title: "Goombrat's cave #TF", difficulty: 2, style: "SMB", tags: ["Boss Battle"] },
    { code: "W3M-9WW-QNF", maker: "Semツ", title: "Ξ Ghσsτ ραlαcε Ξ #TNS #TF", difficulty: 2, style: "NSMBU", tags: ["Short and sweet", "Technical"] },
    { code: "W5H-Y7B-M1G", maker: "PhoenixNL", title: "Valley of Antachamon", difficulty: 2, style: "SM3DW", tags: ["1 CP"] },
    { code: "W93-D28-6PG", maker: "MVXgameS", title: "1-2 Companion Shell Float #TF", difficulty: 2, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "WTM-GMR-RVG", maker: "Dr.Popples", title: "Colorful Destruction #TJ #TF #TS", difficulty: 2, style: "SMW", tags: ["0 CP"] },
    { code: "XG2-BKL-GWF", maker: "lLucer", title: "SLW 3-1ーMoonlight Dynamite", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "Y6R-YCV-KMF", maker: "Dr.Popples", title: "▲ For Honour ▲ #TF #FS #TJ", difficulty: 2, style: "SMB", tags: ["1 CP", "Contest", "FS I"] },
    { code: "YDN-80P-SWG", maker: "SuperBeast", title: "Dawn Over a New World #TF", difficulty: 2, style: "SMW", tags: ["1 CP"] },
    { code: "YQV-SW0-9VF", maker: "JewMstr87", title: "Goomba's Toxic Swamp", difficulty: 2, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "YVL-79G-H8G", maker: "defman144", title: "The jungle of munch", difficulty: 2, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "0GP-N1F-LYG", maker: "lLucer", title: "SLW 2-CーAshes & Snowfall", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "14N-SXQ-9QF", maker: "Pixel_Yosh_Gamer", title: "Boom Booms' Azure Azure #TF", difficulty: 2.5, style: "SMB3", tags: ["Boss battle", "Single player"] },
    { code: "1GK-NBP-62G", maker: "PhoenixNL", title: "Biohazard #TF#FS", difficulty: 2.5, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "212-JNH-KSF", maker: "PhoenixNL", title: "The Jolly Roger", difficulty: 2.5, style: "SMW", tags: ["0 CP"] },
    { code: "2T7-3BW-WYG", maker: "Booster131", title: "Shells and Jamp #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "3DP-7F7-QKF", maker: "Fatality", title: "◇Torrential Treetops◇", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "3L2-0MC-GQG", maker: "Fatality", title: "Pinwheel Forest", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "447-60F-VWG", maker: "Dr.Popples", title: "• Full Metal Impact • #TJ #TF # FS", difficulty: 2.5, style: "NSMBU", tags: ["1 CP"] },
    { code: "485-NN1-52G", maker: "RainbowJaymee", title: "The Flying Frog #teamfantastik'", difficulty: 2.5, style: "SMB3", tags: ["0 CP", "Clear Condition"] },
    { code: "4DW-V8J-C9G", maker: "defman144", title: "2-1 BJG's TTS Spam", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "5DH-GPB-41G", maker: "Dr.Popples", title: "Frosty The Snowbomb #TB #TF", difficulty: 2.5, style: "SMW", tags: ["0 CP"] },
    { code: "603-KVC-NPF", maker: "MickeyRudy", title: "Resident Evil 4 | #TeamShell ", difficulty: 2.5, style: "SMW", tags: ["Technical", "Themed"] },
    { code: "6VC-5JW-F9G", maker: "PhoenixNL", title: "Fallen From Grace", difficulty: 2.5, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "76M-4RP-7TG", maker: "defman144", title: "Big Salty Baby Land #RBC2K #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "7YX-10C-2JF", maker: "bilago", title: "Revenge is a dish surfed cold", difficulty: 2.5, style: "SMW", tags: ["1 CP", "Short & Sweet"] },
    { code: "8T1-60B-YXG", maker: "defman144", title: "Sauce's spooky stroll", difficulty: 2.5, style: "SMW", tags: ["0 CP"] },
    { code: "8XN-F12-CSG", maker: "Cobblepot", title: "Fantastic Elements", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "929-DJQ-BQG", maker: "PhoenixNL", title: "Jungle Cruise #TF", difficulty: 2.5, style: "SM3DW", tags: ["Single player", "Technical"] },
    { code: "9B1-264-YPF", maker: "psycotyca", title: "Shangri-La #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "9BC-TMG-PVF", maker: "psycotyca", title: "#FS: The Shell Embargo", difficulty: 2.5, style: "SMW", tags: ["2 CP", "Contest", "FS V"] },
    { code: "9J8-D28-BDG", maker: "Nelesio", title: "SNW Ω: Spiny Top Lava Cake", difficulty: 2.5, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "9X6-6HT-3MF", maker: "lLucer", title: "SLW 4-2 Triangular Plateau", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "B44-RYC-62G", maker: "Rogervalo", title: "In the nightside of Eden", difficulty: 2.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "BDQ-G9F-4XG", maker: "KnusperBKN", title: "Castle of Delusion [#TJ|#TF]", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "D35-LXW-J3G", maker: "PhoenixNL", title: "Frostbite", difficulty: 2.5, style: "SMW", tags: ["Infinite CP", "Single Player", "Technical"] },
    { code: "D43-F66-QQF", maker: "PhoenixNL", title: "Blaster Cavern", difficulty: 2.5, style: "SM3DW", tags: ["0 CP"] },
    { code: "D4C-Y6F-7LG", maker: "lLucer", title: "SLW 4-1ーShell Hike Dropouts", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "D4W-C3J-N7G", maker: "DragnHntr", title: "The Glenpire Strikes Back", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "D57-1GK-2HF", maker: "lLucer", title: "Rotary Ritual Remastered", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "D91-KGB-PQG", maker: "MVXgameS", title: "4-3 Goomba The Glacial Gladiator", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "DFR-HXJ-H1G", maker: "Dr.Popples", title: "Waddles' Rom-Hack Jungle", difficulty: 2.5, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "DSF-7CB-NSG", maker: "PhoenixNL", title: "Shellday the 13th", difficulty: 2.5, style: "SMB3", tags: ["1 CP"] },
    { code: "DT2-F95-KQF", maker: "Hanzo", title: "Blind Bridge [TF]", difficulty: 2.5, style: "SMW", tags: ["Single Player"] },
    { code: "F2W-BKS-J1G", maker: "defman144", title: "The Fantastik Desert", difficulty: 2.5, style: "SMB3", tags: ["1 CP"] },
    { code: "F4F-4MD-V6G", maker: "JewMstr87", title: "Snowballs From Hell", difficulty: 2.5, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "FDK-JK4-2WF", maker: "lLucer", title: "SLW 4-3ーGateway of the Cave", difficulty: 2.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "FDW-P10-BPG", maker: "RainbowJaymee", title: "Peach Fire Switch #TF", difficulty: 2.5, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "FG0-CWB-LPF", maker: "Quacken", title: "Small Order of Fries #TF", difficulty: 2.5, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "FS5-3HQ-3RF", maker: "Kactus", title: "me when:", difficulty: 2.5, style: "NSMBU", tags: ["Speedrun", "Technical"] },
    { code: "FSP-RKV-D8G", maker: "Booster131", title: "Noeeym's breath of fresh air #TF", difficulty: 2.5, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "FT9-523-C0H", maker: "Y0gamer", title: "Horrifying Heights", difficulty: 2.5, style: "SMW", tags: ["0 CP", "Contest", "FS III"] },
    { code: "FX1-QQ0-Y9G", maker: "KnusperBKN", title: "Mountain of the Missing Shells", difficulty: 2.5, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "G0Q-GNQ-JVG", maker: "PhoenixNL", title: "Mountain Absolnet #TF #FS", difficulty: 2.5, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "GB3-VVC-WRG", maker: "Boops", title: "Rise of Boops: Zestful Zoo", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "GJD-RRM-N1G", maker: "SuperBeastGN", title: "The Brave and the Bold", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "GXY-L31-JPG", maker: "RainbowJaymee", title: "Chef Boyardee Ravioli #TF", difficulty: 2.5, style: "NSMBU", tags: ["Single player", "Technical"] },
    { code: "H3V-K2Y-6MG", maker: "DragnHntr", title: "Surfing T.F. Yay! Team Fantastik", difficulty: 2.5, style: "SMW", tags: ["Boss battle", "Technical"] },
    { code: "J15-5RV-Q3G", maker: "lLucer", title: "SLW 5-1ーStratospheric Express", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "JP0-JRB-5JG", maker: "bigj3llygaming", title: "Gray Sandstone #TF #FS #BJG", difficulty: 2.5, style: "SMW", tags: ["2 CP", "Contains Trolls"] },
    { code: "JVV-6NY-N1G", maker: "Waaddles", title: "A Fantastik Journey #TF", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "KXX-2PQ-S4G", maker: "Keenzzz", title: "Erosion Explosion Commotion #TF", difficulty: 2.5, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "L56-Y1M-3TF", maker: "Dolph1n", title: "Sunshine Daydream #TeamFantastik", difficulty: 2.5, style: "SMW", tags: ["0 CP"] },
    { code: "M5G-K9R-HNF", maker: "psycotyca", title: "Salt & Pepper #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "N7L-F3X-JRF", maker: "Darb", title: "Fruitful Forest #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP", "Contest", "FS II", "Short & Sweet", "Themed"] },
    { code: "NQP-H9M-TCG", maker: "111111", title: "Head Bouncing #TF", difficulty: 2.5, style: "SMB3", tags: ["0 CP", "Clear Condition"] },
    { code: "P83-MP0-XKG", maker: "JewMstr87", title: "NSMBU Precisely Haunted Platforming", difficulty: 2.5, style: "NSMBU", tags: ["Precision"] },
    { code: "PDT-1WG-XWF", maker: "defman144", title: "Stacked Boo Manor", difficulty: 2.5, style: "SMB3", tags: ["0 CP"] },
    { code: "PGK-37P-WJF", maker: "TFLY25", title: "Red Vengeance Kaizo #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "PND-RM5-V0G", maker: "Boops", title: "Rise of Boops: Entry to Shell", difficulty: 2.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "PVJ-C6C-9HG", maker: "Apo", title: "Bowser's Blasters #TS #TF", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "Q7X-0KW-MRF", maker: "defman144", title: "3-1 The Fantastik Voyage", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "QTY-X5C-HRG", maker: "PorkSweater", title: "Hey You, Get Off My Cloud #TF", difficulty: 2.5, style: "SMW", tags: ["0 CP"] },
    { code: "R06-YR4-13G", maker: "youcandoeet", title: "Let's get dizzy with it! #TF", difficulty: 2.5, style: "SMW", tags: ["0 CP"] },
    { code: "RRS-JN3-MGG", maker: "MickeyRudy", title: "Weegee's Wish on Star Hill #TS ", difficulty: 2.5, style: "SMW", tags: ["Short and sweet", "Technical"] },
    { code: "S2R-PXV-1FF", maker: "PhoenixNL", title: "Go Go Froggy Ranger", difficulty: 2.5, style: "SMB3", tags: ["Clear Condition"] },
    { code: "S40-C96-F1G", maker: "DragnHntr", title: "Walter's Jawbone", difficulty: 2.5, style: "SMW", tags: ["Boss Battle"] },
    { code: "SV7-15J-WNF", maker: "RainbowJaymee", title: "The Imposter: Impasta #TF #FS", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "SXC-YY0-B3G", maker: "defman144", title: "Lucid Dreams #TeamFantastik", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "T3T-DNX-P3G", maker: "Adv_Trash", title: "1-2 Donut Be Afraid [Kaizo]", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "TMT-V39-DVG", maker: "RainbowJaymee", title: "69th Anniversary of Mario #TF", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "V0Q-KB8-79G", maker: "Mr._Banghead", title: "Dental Shygiene #TF", difficulty: 2.5, style: "SMB3", tags: ["1 CP", "Technical"] },
    { code: "V1X-QM3-0MF", maker: "lLucer", title: "SLW 3-2ーBombshells", difficulty: 2.5, style: "SMW", tags: ["1 CP"] },
    { code: "VH0-MWQ-7QG", maker: "defman144", title: "Freezing heckin cold!", difficulty: 2.5, style: "SMB3", tags: ["1 CP"] },
    { code: "VM3-KMD-9HF", maker: "ThoThoman", title: "Nobody told me...", difficulty: 2.5, style: "SMB3", tags: ["Single player", "Technical"] },
    { code: "VQ7-VPG-MMF", maker: "lLucer", title: "SLW 4-CーSpring to Action", difficulty: 2.5, style: "SMW", tags: ["2 CP"] },
    { code: "VY0-FCB-79G", maker: "Rogervalo", title: "Don’t fear the reaper", difficulty: 2.5, style: "SMB", tags: ["1 CP"] },
    { code: "W7Q-XRY-94G", maker: "Tic", title: "Myth of the Ancient Ruins", difficulty: 2.5, style: "SMB", tags: ["1 CP"] },
    { code: "WGV-499-XQF", maker: "lLucer", title: "Dragn's Claustrophobic Cavern", difficulty: 2.5, style: "SMB3", tags: ["1 CP"] },
    { code: "WRB-B5G-HPF", maker: "bigj3llygaming", title: "Confined Fortress #TF #FS #BJG", difficulty: 2.5, style: "SMW", tags: ["2 CP", "Contest", "FS I"] },
    { code: "XRS-5WX-HJF", maker: "Adv_Trash", title: "Thorny Stalks in the Clouds #TF", difficulty: 2.5, style: "SMW", tags: ["2 CP", "Themed"] },
    { code: "Y6B-X3S-JXF", maker: "RainbowJaymee", title: "Upside-UP #Teamfantastik", difficulty: 2.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "Y7G-S9G-7PG", maker: "Joshbones", title: "Kazoo #TJ #TF", difficulty: 2.5, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "YQT-N8J-8BG", maker: "NonBasicChaos", title: "6 Chill Chambers #TF #FS", difficulty: 2.5, style: "SMW", tags: ["1 CP", "Contest", "FS I"] },
    { code: "17F-LLC-9WG", maker: "NFNTstones", title: "School of Kaizo: Winter Camp #TF", difficulty: 3, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "1BR-N43-N0H", maker: "Dolph1n", title: "Peppermint Pie #TeamFantastik", difficulty: 3, style: "SMB3", tags: ["Contest", "FS V"] },
    { code: "1DH-VXR-7YF", maker: "ShoeGoomba", title: "Frozen Cave Defrost #TF #FS", difficulty: 3, style: "SMB3", tags: ["1 CP", "Contest", "FS I", "Themed"] },
    { code: "1V3-BXQ-V5G", maker: "Hampl", title: "Stompfall", difficulty: 3, style: "SMB1", tags: ["Technical", "Themed"] },
    { code: "23H-6BL-8GG", maker: "lLucer", title: "SLW 3-AーA Very Unsafe Flight", difficulty: 3, style: "SMW", tags: ["2 CP"] },
    { code: "28R-PC1-RKF", maker: "Tic_y", title: "Grand Mansion #TF", difficulty: 3, style: "SMB3", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "2YS-QHN-MSG", maker: "lLucer", title: "SLW 2-θ Snowgrave", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "33L-J7W-FXG", maker: "Quacken", title: "Boom Boom's Midnite Mile #TJ #TF", difficulty: 3, style: "SMW", tags: ["0 CP", "Clear Condition", "Short & Sweet"] },
    { code: "373-P58-KYG", maker: "psycotyca", title: "Deep Thwomp # TF", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "3BS-MGR-2MF", maker: "Verwalter", title: "Sephirots große Challenge", difficulty: 3, style: "SM3DW", tags: ["0 CP", "Short & Sweet"] },
    { code: "3P4-SDJ-F5G", maker: "PhoenixNL", title: "Romtastik Mansion #TF", difficulty: 3, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "3YF-964-79G", maker: "Dr.Popples", title: "Friday Night Boolin #TF", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "4GD-41N-42G", maker: "Kactus", title: "q", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "4HG-W12-00H", maker: "PhoenixNL", title: "Airfortress Heist", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "5VP-2LL-KPF", maker: "Tic_y", title: "Don't Look Left Cave 10s #TS #TF", difficulty: 3, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "75T-PH4-GQF", maker: "Dolph1n", title: "Snowman #TeamFantastik", difficulty: 3, style: "SMB1", tags: ["Single player", "Technical"] },
    { code: "79C-M0F-WYF", maker: "SaucePowder", title: "Stalagmite", difficulty: 3, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "7FR-GC7-2VF", maker: "defman144", title: "The crimson wave", difficulty: 3, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "84Q-VNX-QQF", maker: "MVXgameS", title: "3-A Mecha-Boot airship #TF", difficulty: 3, style: "SMB3", tags: ["1 CP"] },
    { code: "94Y-XQ8-D1H", maker: "DarthPug", title: "Sobchak Security", difficulty: 3, style: "SMW", tags: ["2 CP"] },
    { code: "99N-JTB-9DG", maker: "lLucer", title: "Lonk's Midnight Misdemeanor", difficulty: 3, style: "SMB", tags: ["0 CP", "Clear Condition", "Link", "Short & Sweet"] },
    { code: "BBT-QGN-N3G", maker: "Joshbones", title: "Eleanor Rigby", difficulty: 3, style: "SMW", tags: ["1 CP", "Technical"] },
    { code: "BVY-B9D-J7G", maker: "Hanzo", title: "[]Mansion of Many Munchers[]", difficulty: 3, style: "SMW", tags: ["Precision"] },
    { code: "G3N-6LH-Q0H", maker: "lLucer", title: "SLW 3-3ーTicking Timebomb", difficulty: 3, style: "SMW", tags: ["0 CP"] },
    { code: "G4L-7LN-5WF", maker: "MarioMakerFan", title: "Springs And Blue Platforms #TF", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "G7Q-0RW-8VG", maker: "Joshbones", title: "Bop It!", difficulty: 3, style: "SMW", tags: ["2 CP", "Contest", "FS IV"] },
    { code: "G7Q-GDG-XKF", maker: "Rogervalo", title: "Sleepwalking past hope", difficulty: 3, style: "SM3DW", tags: ["0 CP"] },
    { code: "H1Y-CN4-9XG", maker: "Booster131", title: "Bongo Realbchin In Space #TF", difficulty: 3, style: "NSMBU", tags: ["0 CP", "Clear Condition"] },
    { code: "HP2-MJ2-9LG", maker: "neeodev", title: "Neeo Skill - Jumping Mices !", difficulty: 3, style: "SM3DW", tags: ["0 CP"] },
    { code: "KD3-VV3-8GF", maker: "jevarel_UXB_56X-V1N-6JF", title: "Danger UXB 7.5 #TeamFantastik", difficulty: 3, style: "SM3DW", tags: ["1 CP"] },
    { code: "L94-FXB-NHF", maker: "PhoenixNL", title: "The Thwomp'n'Chomp Connection", difficulty: 3, style: "SMW", tags: ["Contest", "FS IV"] },
    { code: "LGC-1TR-WXG", maker: "psycotyca", title: "Mixed Kaizo Arts: The BombThwomp", difficulty: 3, style: "SMW", tags: ["0 CP"] },
    { code: "MXC-LX4-KYG", maker: "Nelesio", title: "SNW Omega: Space Jam #TJ #TF", difficulty: 3, style: "SMB3", tags: ["1 CP"] },
    { code: "NHG-3NN-RHF", maker: "Dolph1n", title: "Chocolate Diesel #TeamFantastik", difficulty: 3, style: "SMW", tags: ["1 CP", "Contest", "FS II"] },
    { code: "PDB-X95-PWG", maker: "tflynnie25", title: "Violet Vengeance Kaizo #TF", difficulty: 3, style: "SMW", tags: ["2 CP"] },
    { code: "PLQ-DB6-9QF", maker: "lLucer", title: "Enceladus #TF", difficulty: 3, style: "SMW", tags: ["0 CP", "Single Player"] },
    { code: "PPW-LWM-KDG", maker: "PhoenixNL", title: "Blast-Off: Apollo 13", difficulty: 3, style: "NSMBU", tags: ["0 CP"] },
    { code: "Q43-8P1-7RF", maker: "defman144", title: "Mario gets boosted", difficulty: 3, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "QH0-2VP-SHF", maker: "Y0gamer", title: "Frosted Chomp Thwomps", difficulty: 3, style: "SMW", tags: ["0 CP"] },
    { code: "RF6-829-QWG", maker: "defman144", title: "Surfin Safari", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "SB9-G98-5GG", maker: "PhoenixNL", title: "Yoshi's Boneyard", difficulty: 3, style: "SMW", tags: ["0 CP"] },
    { code: "SJN-2MM-12G", maker: "bigj3llygaming", title: "Blue Raspberry Sherbet#TF#FS#BJG", difficulty: 3, style: "SMW", tags: ["1 CP"] },
    { code: "T6L-0X3-LHF", maker: "RedDungeon", title: "Red's FUNgeon with Victims 3", difficulty: 3, style: "SMB3", tags: ["2 CP"] },
    { code: "T6Q-G88-KNF", maker: "HighLow", title: "Treacherous Tundra #TF", difficulty: 3, style: "SMB", tags: ["2 CP", "Themed"] },
    { code: "T82-1D4-J5G", maker: "RainbowJaymee", title: "Community Chest #TF", difficulty: 3, style: "SMW", tags: ["1 CP", "Single Player", "Technical"] },
    { code: "TDR-KVS-LNF", maker: "PhoenixNL", title: "4 Chambers of Anubis #FS #TF", difficulty: 3, style: "SMW", tags: ["2 CP", "Contest", "FS I"] },
    { code: "TGW-V7Q-HSF", maker: "Joshbones", title: "Where's my Z? #TF #TJ", difficulty: 3, style: "SMW", tags: ["Contest", "FS V"] },
    { code: "TXK-8KL-TRF", maker: "PhoenixNL", title: "Magma Vortex", difficulty: 3, style: "SMW", tags: ["0 CP"] },
    { code: "V6P-WGC-XRG", maker: "defman144", title: "The Fantastik flooded castle", difficulty: 3, style: "SMW", tags: ["1 CP", "Single Player", "Technical"] },
    { code: "VVM-T4Y-40H", maker: "JurassicLucas", title: "Merry Madness", difficulty: 3, style: "SMB3", tags: ["Short and sweet", "Single player"] },
    { code: "W1K-W14-KJG", maker: "MVXgameS", title: "2-3 Rainbow Pipe Ride #TF", difficulty: 3, style: "NSMBU", tags: ["0 CP"] },
    { code: "XMP-QFS-06G", maker: "Hanzo", title: "[Desert Doublechu]", difficulty: 3, style: "SMW", tags: ["Single Player"] },
    { code: "Y6N-1YF-NHF", maker: "defman144", title: "Oasis of lost shells #TF", difficulty: 3, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "0GM-9G0-RVG", maker: "Cobblepot", title: "A Blutiful Mind", difficulty: 3.5, style: "SMW", tags: ["2 CP"] },
    { code: "1B1-52F-9PF", maker: "bigj3llygaming", title: "Snowshells? #TF #BJG ", difficulty: 3.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "2G5-N1M-XSG", maker: "Dolph1n", title: "Jillybean #TeamFantastik", difficulty: 3.5, style: "SMW", tags: ["1 CP", "Technical"] },
    { code: "4LS-YCL-CDF", maker: "RainbowJaymee", title: "Just Another Castle Remix #TF", difficulty: 3.5, style: "SMW", tags: ["2 CP"] },
    { code: "4TD-7XM-2NG", maker: "defman144", title: "The trail of tears", difficulty: 3.5, style: "SMW", tags: ["0 CP"] },
    { code: "5CQ-NTY-8WF", maker: "DragnHntr", title: "Cheesy P & The Shell Jump Spree", difficulty: 3.5, style: "SMW", tags: ["2 CP"] },
    { code: "9B5-BWR-XXG", maker: "Dolph1n", title: "Sweet Pea #TeamFantastik", difficulty: 3.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "B6D-7ND-B8G", maker: "Booster131", title: "BigRedBoy's Snowy Day! #TF", difficulty: 3.5, style: "SMW", tags: ["1 CP"] },
    { code: "D1J-8J1-7WG", maker: "H34DHVN7R", title: "SMW Escape From Snowland #TF", difficulty: 3.5, style: "SMW", tags: ["0 CP"] },
    { code: "DCS-DGQ-XSF", maker: "MVXgameS", title: "3-2 Mt. Thwomp-Chomp Climb! #TF", difficulty: 3.5, style: "NSMBU", tags: ["2 CP"] },
    { code: "F07-XXG-SHF", maker: "psycotyca", title: "ShellTrek 2 #TS#TF", difficulty: 3.5, style: "SMW", tags: ["Technical", "Themed"] },
    { code: "FHJ-P1L-9TF", maker: "defman144", title: "The School Of Hard Blocks", difficulty: 3.5, style: "SMW", tags: ["0 CP"] },
    { code: "FX1-G4P-RWG", maker: "RainbowJaymee", title: "YoshMan Kaizo #Teamfantastik", difficulty: 3.5, style: "SMW", tags: ["0 CP"] },
    { code: "M4C-67Q-MGG", maker: "PhoenixNL", title: "Feeling the Heat #TF #FS", difficulty: 3.5, style: "SMW", tags: ["Contest", "FS III"] },
    { code: "NLQ-GWD-6FG", maker: "RainbowJaymee", title: "Power Switch Kaizo 3DW #TF", difficulty: 3.5, style: "SM3DW", tags: ["Clear Condition"] },
    { code: "NY8-DWP-6RF", maker: "defman144", title: "Get lifted!", difficulty: 3.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "PGB-K78-V9G", maker: "Enimit", title: "Bolter", difficulty: 3.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "R06-PM6-LCG", maker: "RainbowJaymee", title: "The Amazing Spider-Man #TF", difficulty: 3.5, style: "SMW", tags: ["2 CP"] },
    { code: "RHV-9R3-MXF", maker: "psycotyca", title: "Mixed Kaizo Arts #TF #TJ", difficulty: 3.5, style: "SMW", tags: ["Single player", "Themed"] },
    { code: "YQY-4KP-0YF", maker: "Dr.Popples", title: "Risky Platforming | Footlong #TF", difficulty: 3.5, style: "SMB3", tags: ["2 CP"] },
    { code: "1XK-3QP-H9G", maker: "MVXgameS", title: "2-2 Goombrats Icy Claustrophobia", difficulty: 4, style: "SMB", tags: ["0 CP", "Short & Sweet"] },
    { code: "6FV-GWB-XCG", maker: "MVXgameS", title: "Fiery Botanist Airship #TF", difficulty: 4, style: "SMW", tags: ["0 CP", "Clear Condition"] },
    { code: "7D8-FMP-RYF", maker: "Dr.Popples", title: "-Dimension Breaker-", difficulty: 4, style: "SMB3", tags: ["1 CP"] },
    { code: "P2R-Y5T-DWF", maker: "Dolph1n", title: "Silver Haze #TeamFanastik", difficulty: 4, style: "SMW", tags: ["0 CP", "Short & Sweet"] },
    { code: "P7X-GPN-RBG", maker: "RainbowJaymee", title: "It Was Just A Dream #TF", difficulty: 4, style: "SMW", tags: ["2 CP"] },
    { code: "PBH-YJP-BJG", maker: "Booster131", title: "Cinthia's Lava Cruise #TF", difficulty: 4, style: "NSMBU", tags: ["0 CP", "Short & Sweet"] },
    { code: "TS9-FR5-86G", maker: "Dr.Popples", title: "△ Kaizo Mountain △ #TF", difficulty: 4, style: "SMW", tags: ["2 CP"] },
    { code: "YSC-07D-55G", maker: "PhoenixNL", title: "Cursed Mansion #TF #TS", difficulty: 4, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "186-L3P-5NG", maker: "lLucer", title: "Fallen Angel #TeamFantastik", difficulty: 4.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "FQ3-FKW-09G", maker: "Insulin", title: "Gloomy Garden", difficulty: 4.5, style: "SMW", tags: ["0 CP", "Clear Condition"] },
    { code: "T6D-CPL-71G", maker: "Booster131", title: "Needaboost 5: Rush Hour! #TF #FS", difficulty: 4.5, style: "SMW", tags: ["1 CP", "Contest", "FS I"] },
    { code: "TD7-9LN-SKG", maker: "Charisma", title: "A Fantastik ROM", difficulty: 4.5, style: "SMW", tags: ["0 CP"] },
    { code: "3Y2-WM8-DXG", maker: "Crumpnpump", title: "Anguish #TF", difficulty: 5, style: "SMW", tags: ["Standard", "Technical"] },
    { code: "498-KLG-RQF", maker: "defman144", title: "SJL_TV caverns #TF", difficulty: 5, style: "SMW", tags: ["1 CP"] },
    { code: "Q95-D3S-KFG", maker: "defman144", title: "Sixty Ninth Level Extravaganza!", difficulty: 5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "R23-W30-RLG", maker: "Dr.Popples", title: "Wrath Of Popples | Lunch Box #TF", difficulty: 5, style: "SM3DW", tags: ["0 CP", "Clear Condition"] },
    { code: "6S9-LN9-39G", maker: "psycotyca", title: "Mixed Kaizo Arts: The Bullet Mill", difficulty: 5.5, style: "SMW", tags: ["Single Player", "Technical"] },
    { code: "F30-XKK-S2G", maker: "Y0gamer", title: "Primitive plains", difficulty: 5.5, style: "SMW", tags: ["0 CP"] },
    { code: "GNT-6WX-JVF", maker: "SaltLakeAtrocity", title: "Verdelet", difficulty: 5.5, style: "SMB", tags: ["2 CP"] },
    { code: "XRH-2RH-5NG", maker: "TooPlaya", title: "Truffle Shuffle #TF", difficulty: 5.5, style: "SMB", tags: ["1 CP"] },
    { code: "D94-LPT-XMG", maker: "Dr.Popples", title: "[ Rise of Kaizo Dude ]", difficulty: 6, style: "SMW", tags: ["0 CP"] },
    { code: "XTQ-MVW-TPF", maker: "Rogervalo", title: "Alicization", difficulty: 6, style: "SMW", tags: ["0 CP"] },
    { code: "BQY-9XN-MFG", maker: "SaltLakeAtrocity", title: "Paranova", difficulty: 6.5, style: "SMW", tags: ["Single player", "Technical"] },
    { code: "T6G-2SS-VWF", maker: "Verwalter", title: "Verwalter's Final Level", difficulty: 6.5, style: "SM3DW", tags: ["0 CP", "Clear Condition"] },
    { code: "VGK-PT3-RLF", maker: "JC", title: "SMW JCs #TF Aint Nuthing ta Mess Wit", difficulty: 7, style: "SMW", tags: ["Speedrun", "Technical"] },
];
